-- Voxalia auth/security baseline.
-- Idempotent by design: safe to run repeatedly in phase 0 environments.

create table if not exists public.tenants (
  id bigint generated by default as identity primary key,
  tenant_key text not null unique,
  display_name text not null,
  legal_name text,
  vertical text not null default 'hospitality',
  timezone text not null default 'America/Costa_Rica',
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenants_status_ck check (status in ('active', 'inactive', 'suspended')),
  constraint tenants_vertical_ck check (vertical in ('hospitality', 'internal', 'other'))
);

create table if not exists public.auth_users (
  id bigint generated by default as identity primary key,
  username text not null,
  email text not null,
  display_name text not null,
  password_hash text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint auth_users_status_ck check (status in ('active', 'inactive', 'locked'))
);

create unique index if not exists auth_users_username_lower_key
  on public.auth_users (lower(username));

create unique index if not exists auth_users_email_lower_key
  on public.auth_users (lower(email));

create table if not exists public.auth_roles (
  id text primary key,
  label text not null,
  scope text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  constraint auth_roles_scope_ck check (scope in ('system', 'tenant'))
);

create table if not exists public.auth_permissions (
  id text primary key,
  label text not null,
  description text not null default ''
);

create table if not exists public.auth_role_permissions (
  role_id text not null references public.auth_roles(id) on delete cascade,
  permission_id text not null references public.auth_permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);

create table if not exists public.auth_user_roles (
  user_id bigint not null references public.auth_users(id) on delete cascade,
  role_id text not null references public.auth_roles(id) on delete restrict,
  primary key (user_id, role_id)
);

create table if not exists public.auth_user_tenants (
  user_id bigint not null references public.auth_users(id) on delete cascade,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (user_id, tenant_id)
);

create table if not exists public.auth_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.auth_users(id) on delete cascade,
  session_token_hash text not null unique,
  active_tenant_id bigint references public.tenants(id) on delete set null,
  active_role_id text references public.auth_roles(id) on delete set null,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz,
  expires_at timestamptz not null,
  revoked_at timestamptz
);

create table if not exists public.auth_password_reset_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.auth_users(id) on delete cascade,
  delivery_email text not null,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz
);

create table if not exists public.auth_audit_log (
  id bigint generated by default as identity primary key,
  user_id bigint references public.auth_users(id) on delete set null,
  tenant_id bigint references public.tenants(id) on delete set null,
  action text not null,
  subject_type text not null,
  subject_id text,
  ip_address inet,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists tenants_status_idx
  on public.tenants(status);

create index if not exists auth_user_tenants_tenant_idx
  on public.auth_user_tenants(tenant_id);

create index if not exists auth_sessions_token_hash_idx
  on public.auth_sessions(session_token_hash);

create index if not exists auth_sessions_user_active_idx
  on public.auth_sessions(user_id, expires_at)
  where revoked_at is null;

create index if not exists auth_password_reset_tokens_user_idx
  on public.auth_password_reset_tokens(user_id, created_at desc);

create index if not exists auth_password_reset_tokens_active_idx
  on public.auth_password_reset_tokens(token_hash, expires_at)
  where used_at is null;

create index if not exists auth_audit_log_created_idx
  on public.auth_audit_log(created_at desc);

create index if not exists auth_audit_log_tenant_created_idx
  on public.auth_audit_log(tenant_id, created_at desc);

create or replace function public.voxalia_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tenants_set_updated_at on public.tenants;
create trigger tenants_set_updated_at
before update on public.tenants
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists auth_users_set_updated_at on public.auth_users;
create trigger auth_users_set_updated_at
before update on public.auth_users
for each row execute function public.voxalia_set_updated_at();

insert into public.tenants (id, tenant_key, display_name, legal_name, vertical, timezone, status, metadata)
values (
  1,
  'voxalia',
  'Voxalia',
  'Voxalia',
  'internal',
  'America/Costa_Rica',
  'active',
  '{"kind":"internal"}'::jsonb
)
on conflict (id) do update set
  tenant_key = excluded.tenant_key,
  display_name = excluded.display_name,
  legal_name = excluded.legal_name,
  vertical = excluded.vertical,
  timezone = excluded.timezone,
  status = excluded.status,
  metadata = excluded.metadata,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.tenants', 'id'),
  greatest((select coalesce(max(id), 1) from public.tenants), 1)
);

insert into public.auth_roles (id, label, scope, description)
values
  ('system_admin', 'System admin', 'system', 'Full platform control, including security, tenants and infrastructure-facing configuration.'),
  ('admin', 'Admin', 'system', 'Voxalia operations administrator for call center configuration and day-to-day operations.'),
  ('supervisor', 'Supervisor', 'system', 'Voxalia call center supervisor with visibility into agent activity, recordings and reports.'),
  ('agent', 'Agent', 'system', 'Voxalia call center agent who handles tenant-scoped interactions.'),
  ('client_admin', 'Client admin', 'tenant', 'Tenant-side administrator for users, reporting preferences and allowed partner settings.'),
  ('client', 'Client', 'tenant', 'Tenant-side read-only or limited portal user.')
on conflict (id) do update set
  label = excluded.label,
  scope = excluded.scope,
  description = excluded.description;

insert into public.auth_permissions (id, label, description)
values
  ('auth:users:manage', 'Manage users', 'Create, edit, deactivate and assign users.'),
  ('auth:roles:manage', 'Manage roles', 'Maintain roles and permission grants.'),
  ('tenants:manage', 'Manage tenants', 'Create and maintain tenants/partners.'),
  ('tenants:read', 'Read tenants', 'Read tenant/partner configuration.'),
  ('voice:operate', 'Operate calls', 'Answer, place, hold, transfer and conference calls.'),
  ('voice:configure', 'Configure voice', 'Maintain numbers, trunks, routes, queues and recording policies.'),
  ('voice:recordings:read', 'Read recordings', 'Access tenant-scoped call recordings when policy allows.'),
  ('voice:recordings:manage', 'Manage recordings', 'Manage recording retention, legal hold and operational exceptions.'),
  ('conversations:read', 'Read conversations', 'Read tenant-scoped conversations and interactions.'),
  ('conversations:manage', 'Manage conversations', 'Create notes, outcomes, tasks and opportunities.'),
  ('reports:read', 'Read reports', 'Access tenant-scoped reports and dashboards.'),
  ('reports:manage', 'Manage reports', 'Configure report delivery and recipients.'),
  ('channels:configure', 'Configure channels', 'Maintain voice, Chatwoot, webchat, WhatsApp and email channels.'),
  ('integrations:configure', 'Configure integrations', 'Maintain PMS, CRM, payment, mail and provider connectors.'),
  ('audit:read', 'Read audit log', 'Read security and operational audit trails.'),
  ('ai:jobs:manage', 'Manage AI jobs', 'Run or administer transcription, summaries, QA and extraction jobs.')
on conflict (id) do update set
  label = excluded.label,
  description = excluded.description;

insert into public.auth_role_permissions (role_id, permission_id)
select 'system_admin', id from public.auth_permissions
on conflict do nothing;

insert into public.auth_role_permissions (role_id, permission_id)
values
  ('admin', 'tenants:read'),
  ('admin', 'voice:operate'),
  ('admin', 'voice:configure'),
  ('admin', 'voice:recordings:read'),
  ('admin', 'conversations:read'),
  ('admin', 'conversations:manage'),
  ('admin', 'reports:read'),
  ('admin', 'reports:manage'),
  ('admin', 'channels:configure'),
  ('admin', 'integrations:configure'),
  ('admin', 'audit:read'),
  ('admin', 'ai:jobs:manage'),
  ('supervisor', 'tenants:read'),
  ('supervisor', 'voice:operate'),
  ('supervisor', 'voice:recordings:read'),
  ('supervisor', 'conversations:read'),
  ('supervisor', 'conversations:manage'),
  ('supervisor', 'reports:read'),
  ('supervisor', 'audit:read'),
  ('agent', 'tenants:read'),
  ('agent', 'voice:operate'),
  ('agent', 'conversations:read'),
  ('agent', 'conversations:manage'),
  ('client_admin', 'tenants:read'),
  ('client_admin', 'voice:recordings:read'),
  ('client_admin', 'conversations:read'),
  ('client_admin', 'reports:read'),
  ('client_admin', 'reports:manage'),
  ('client', 'tenants:read'),
  ('client', 'conversations:read'),
  ('client', 'reports:read')
on conflict do nothing;
