-- Voxalia tenant workspace foundation.
-- Idempotent by design: safe to run repeatedly in phase 0 environments.

create table if not exists public.tenant_product_subscriptions (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  product_key text not null,
  display_name text not null,
  status text not null default 'active',
  activated_at timestamptz,
  cancelled_at timestamptz,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_product_subscriptions_status_ck check (status in ('active', 'trial', 'paused', 'cancelled')),
  constraint tenant_product_subscriptions_product_key_ck check (product_key in ('managed-reception', 'multichannel-inbox', 'call-intelligence', 'agent-assist', 'automated-chat', 'sales-followup')),
  constraint tenant_product_subscriptions_active_dates_ck check (cancelled_at is null or activated_at is null or cancelled_at >= activated_at),
  unique (id, tenant_id),
  unique (tenant_id, product_key)
);

create table if not exists public.tenant_service_policies (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  policy_key text not null,
  display_name text not null,
  status text not null default 'active',
  default_language text not null default 'en',
  supported_languages text[] not null default array['en']::text[],
  after_hours_behavior text not null default 'take_message',
  callback_window text,
  recording_disclosure text not null default '',
  recording_retention_days integer not null default 365,
  escalation_notes text not null default '',
  agent_notes text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_service_policies_status_ck check (status in ('active', 'inactive', 'draft')),
  constraint tenant_service_policies_after_hours_behavior_ck check (after_hours_behavior in ('take_message', 'callback_next_business_day', 'emergency_only', 'transfer_to_partner', 'closed_message')),
  constraint tenant_service_policies_recording_retention_days_ck check (recording_retention_days > 0),
  unique (id, tenant_id),
  unique (tenant_id, policy_key)
);

create table if not exists public.tenant_service_hours (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  service_policy_id bigint references public.tenant_service_policies(id) on delete cascade,
  weekday smallint not null,
  starts_at time,
  ends_at time,
  is_closed boolean not null default false,
  label text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_service_hours_weekday_ck check (weekday between 0 and 6),
  constraint tenant_service_hours_window_ck check (
    (is_closed and starts_at is null and ends_at is null)
    or (not is_closed and starts_at is not null and ends_at is not null and starts_at < ends_at)
  ),
  constraint tenant_service_hours_policy_tenant_fk foreign key (service_policy_id, tenant_id)
    references public.tenant_service_policies(id, tenant_id) on delete cascade
);

create table if not exists public.tenant_channels (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  service_policy_id bigint,
  channel_key text not null,
  channel_type text not null,
  display_name text not null,
  provider text not null default 'voxalia',
  routing_key text not null default '',
  default_language text not null default 'en',
  status text not null default 'active',
  recording_required boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_channels_type_ck check (channel_type in ('voice_toll_free', 'voice_local', 'chatwoot_inbox', 'voxalia_webchat', 'meta_whatsapp', 'email')),
  constraint tenant_channels_status_ck check (status in ('active', 'inactive', 'provisioning', 'failed')),
  constraint tenant_channels_policy_tenant_fk foreign key (service_policy_id, tenant_id)
    references public.tenant_service_policies(id, tenant_id),
  unique (id, tenant_id),
  unique (tenant_id, channel_key),
  unique (tenant_id, channel_type, routing_key)
);

create table if not exists public.voice_numbers (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  channel_id bigint,
  number_e164 text not null,
  label text not null,
  number_type text not null,
  country_code text not null default 'US',
  status text not null default 'active',
  recording_required boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint voice_numbers_type_ck check (number_type in ('toll_free', 'local', 'extension', 'outbound_caller_id')),
  constraint voice_numbers_status_ck check (status in ('active', 'inactive', 'provisioning', 'failed', 'released')),
  constraint voice_numbers_channel_tenant_fk foreign key (channel_id, tenant_id)
    references public.tenant_channels(id, tenant_id),
  unique (id, tenant_id),
  unique (number_e164)
);

create table if not exists public.tenant_contacts (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  display_name text not null,
  organization text not null default '',
  department text not null default '',
  title text not null default '',
  contact_type text not null default 'other',
  priority integer not null default 100,
  status text not null default 'active',
  notes text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_contacts_type_ck check (contact_type in ('admin', 'billing', 'operations', 'reservations', 'sales', 'emergency', 'reporting', 'technical', 'other')),
  constraint tenant_contacts_status_ck check (status in ('active', 'inactive')),
  constraint tenant_contacts_priority_ck check (priority >= 0),
  unique (id, tenant_id)
);

create table if not exists public.tenant_contact_methods (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  contact_id bigint not null references public.tenant_contacts(id) on delete cascade,
  method_type text not null,
  label text not null default '',
  value text not null,
  is_primary boolean not null default false,
  can_receive_escalations boolean not null default false,
  availability text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_contact_methods_type_ck check (method_type in ('phone', 'email', 'sms', 'whatsapp', 'extension')),
  constraint tenant_contact_methods_contact_tenant_fk foreign key (contact_id, tenant_id)
    references public.tenant_contacts(id, tenant_id) on delete cascade,
  unique (contact_id, method_type, value)
);

create table if not exists public.agent_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.auth_users(id) on delete cascade,
  display_name text not null,
  languages text[] not null default array['en']::text[],
  skills text[] not null default array[]::text[],
  status text not null default 'offline',
  supervisor_user_id bigint references public.auth_users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_profiles_status_ck check (status in ('offline', 'available', 'ringing', 'on_call', 'after_call_work', 'break', 'training', 'unavailable')),
  unique (id, user_id),
  unique (user_id)
);

create table if not exists public.tenant_agent_assignments (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  agent_profile_id bigint not null references public.agent_profiles(id) on delete cascade,
  assignment_type text not null default 'primary',
  queue_key text not null default '',
  priority integer not null default 100,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_agent_assignments_type_ck check (assignment_type in ('primary', 'backup', 'supervisor', 'specialist')),
  constraint tenant_agent_assignments_status_ck check (status in ('active', 'inactive')),
  constraint tenant_agent_assignments_priority_ck check (priority >= 0),
  unique (id, tenant_id),
  unique (tenant_id, agent_profile_id, assignment_type, queue_key)
);

create table if not exists public.tenant_scripts (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  channel_id bigint,
  service_policy_id bigint,
  script_key text not null,
  script_type text not null,
  title text not null,
  language text not null default 'en',
  body text not null,
  status text not null default 'draft',
  version integer not null default 1,
  effective_from timestamptz,
  effective_to timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_scripts_type_ck check (script_type in ('greeting', 'intake', 'escalation', 'after_hours', 'disclosure', 'faq', 'handoff', 'other')),
  constraint tenant_scripts_status_ck check (status in ('draft', 'active', 'retired')),
  constraint tenant_scripts_version_ck check (version > 0),
  constraint tenant_scripts_effective_window_ck check (effective_to is null or effective_from is null or effective_to > effective_from),
  constraint tenant_scripts_channel_tenant_fk foreign key (channel_id, tenant_id)
    references public.tenant_channels(id, tenant_id),
  constraint tenant_scripts_policy_tenant_fk foreign key (service_policy_id, tenant_id)
    references public.tenant_service_policies(id, tenant_id),
  unique (id, tenant_id),
  unique (tenant_id, script_key, language, version)
);

create table if not exists public.reporting_recipients (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  contact_id bigint,
  display_name text not null,
  email text not null,
  report_type text not null default 'management_summary',
  cadence text not null default 'weekly',
  timezone text not null default 'America/Costa_Rica',
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reporting_recipients_type_ck check (report_type in ('management_summary', 'call_history', 'opportunities', 'quality', 'billing', 'custom')),
  constraint reporting_recipients_cadence_ck check (cadence in ('daily', 'weekly', 'monthly', 'on_demand')),
  constraint reporting_recipients_status_ck check (status in ('active', 'inactive')),
  constraint reporting_recipients_contact_tenant_fk foreign key (contact_id, tenant_id)
    references public.tenant_contacts(id, tenant_id),
  unique (id, tenant_id),
  unique (tenant_id, email, report_type)
);

create index if not exists tenant_product_subscriptions_tenant_idx
  on public.tenant_product_subscriptions(tenant_id, status);

create index if not exists tenant_service_policies_tenant_idx
  on public.tenant_service_policies(tenant_id, status);

create index if not exists tenant_service_hours_tenant_weekday_idx
  on public.tenant_service_hours(tenant_id, weekday);

create index if not exists tenant_channels_tenant_type_idx
  on public.tenant_channels(tenant_id, channel_type, status);

create index if not exists voice_numbers_tenant_status_idx
  on public.voice_numbers(tenant_id, status);

create index if not exists tenant_contacts_tenant_type_idx
  on public.tenant_contacts(tenant_id, contact_type, status);

create index if not exists tenant_contact_methods_tenant_idx
  on public.tenant_contact_methods(tenant_id, method_type);

create index if not exists agent_profiles_status_idx
  on public.agent_profiles(status);

create index if not exists tenant_agent_assignments_tenant_idx
  on public.tenant_agent_assignments(tenant_id, status);

create index if not exists tenant_scripts_tenant_type_idx
  on public.tenant_scripts(tenant_id, script_type, status);

create index if not exists reporting_recipients_tenant_idx
  on public.reporting_recipients(tenant_id, status);

drop trigger if exists tenant_product_subscriptions_set_updated_at on public.tenant_product_subscriptions;
create trigger tenant_product_subscriptions_set_updated_at
before update on public.tenant_product_subscriptions
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists tenant_service_policies_set_updated_at on public.tenant_service_policies;
create trigger tenant_service_policies_set_updated_at
before update on public.tenant_service_policies
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists tenant_service_hours_set_updated_at on public.tenant_service_hours;
create trigger tenant_service_hours_set_updated_at
before update on public.tenant_service_hours
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists tenant_channels_set_updated_at on public.tenant_channels;
create trigger tenant_channels_set_updated_at
before update on public.tenant_channels
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists voice_numbers_set_updated_at on public.voice_numbers;
create trigger voice_numbers_set_updated_at
before update on public.voice_numbers
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists tenant_contacts_set_updated_at on public.tenant_contacts;
create trigger tenant_contacts_set_updated_at
before update on public.tenant_contacts
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists tenant_contact_methods_set_updated_at on public.tenant_contact_methods;
create trigger tenant_contact_methods_set_updated_at
before update on public.tenant_contact_methods
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists agent_profiles_set_updated_at on public.agent_profiles;
create trigger agent_profiles_set_updated_at
before update on public.agent_profiles
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists tenant_agent_assignments_set_updated_at on public.tenant_agent_assignments;
create trigger tenant_agent_assignments_set_updated_at
before update on public.tenant_agent_assignments
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists tenant_scripts_set_updated_at on public.tenant_scripts;
create trigger tenant_scripts_set_updated_at
before update on public.tenant_scripts
for each row execute function public.voxalia_set_updated_at();

drop trigger if exists reporting_recipients_set_updated_at on public.reporting_recipients;
create trigger reporting_recipients_set_updated_at
before update on public.reporting_recipients
for each row execute function public.voxalia_set_updated_at();

insert into public.tenant_product_subscriptions (tenant_id, product_key, display_name, status, activated_at, config)
select id, 'managed-reception', 'Managed Reception', 'active', now(), '{"phase":"foundation"}'::jsonb
from public.tenants
where tenant_key = 'voxalia'
on conflict (tenant_id, product_key) do update set
  display_name = excluded.display_name,
  status = excluded.status,
  config = excluded.config,
  updated_at = now();

insert into public.tenant_service_policies (
  tenant_id,
  policy_key,
  display_name,
  status,
  default_language,
  supported_languages,
  after_hours_behavior,
  recording_disclosure,
  recording_retention_days,
  agent_notes
)
select
  id,
  'default',
  'Default managed reception policy',
  'active',
  'en',
  array['en', 'es']::text[],
  'take_message',
  'Calls may be recorded for quality and service follow-up.',
  365,
  'Initial internal policy for workspace wiring.'
from public.tenants
where tenant_key = 'voxalia'
on conflict (tenant_id, policy_key) do update set
  display_name = excluded.display_name,
  status = excluded.status,
  default_language = excluded.default_language,
  supported_languages = excluded.supported_languages,
  after_hours_behavior = excluded.after_hours_behavior,
  recording_disclosure = excluded.recording_disclosure,
  recording_retention_days = excluded.recording_retention_days,
  agent_notes = excluded.agent_notes,
  updated_at = now();
