-- Voxalia operations, voice, integration, AI and audit foundation.
-- Idempotent by design for phase 0 environments.
-- This migration models Voxalia-owned operational data. It does not duplicate
-- FreePBX/Asterisk internal configuration such as SIP trunks, PJSIP endpoints,
-- dialplan internals, devices, passwords or queue member management.

create table if not exists public.conversation_contacts (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  display_name text not null,
  first_name text not null default '',
  last_name text not null default '',
  organization text not null default '',
  email text,
  phone_e164 text,
  whatsapp_e164 text,
  language text not null default 'en',
  contact_type text not null default 'caller',
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversation_contacts_type_ck check (contact_type in ('caller', 'guest', 'lead', 'traveler', 'group_organizer', 'business', 'external_partner', 'other')),
  constraint conversation_contacts_status_ck check (status in ('active', 'inactive')),
  unique (id, tenant_id)
);

create table if not exists public.conversation_conversations (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  primary_contact_id bigint,
  conversation_key text not null,
  subject text not null,
  status text not null default 'open',
  priority text not null default 'normal',
  source_channel_id bigint,
  assigned_user_id bigint references public.auth_users(id) on delete set null,
  opened_at timestamptz not null default now(),
  last_interaction_at timestamptz,
  closed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversation_conversations_status_ck check (status in ('open', 'pending', 'resolved', 'closed')),
  constraint conversation_conversations_priority_ck check (priority in ('low', 'normal', 'high', 'urgent')),
  constraint conversation_conversations_primary_contact_fk foreign key (primary_contact_id, tenant_id)
    references public.conversation_contacts(id, tenant_id),
  constraint conversation_conversations_source_channel_fk foreign key (source_channel_id, tenant_id)
    references public.tenant_channels(id, tenant_id),
  constraint conversation_conversations_closed_at_ck check (closed_at is null or closed_at >= opened_at),
  unique (id, tenant_id),
  unique (tenant_id, conversation_key)
);

create table if not exists public.conversation_participants (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  conversation_id bigint not null,
  participant_type text not null,
  contact_id bigint,
  user_id bigint references public.auth_users(id) on delete set null,
  tenant_contact_id bigint,
  role text not null default 'participant',
  display_name text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversation_participants_type_ck check (participant_type in ('conversation_contact', 'voxalia_user', 'tenant_contact', 'system')),
  constraint conversation_participants_conversation_fk foreign key (conversation_id, tenant_id)
    references public.conversation_conversations(id, tenant_id) on delete cascade,
  constraint conversation_participants_contact_fk foreign key (contact_id, tenant_id)
    references public.conversation_contacts(id, tenant_id),
  constraint conversation_participants_tenant_contact_fk foreign key (tenant_contact_id, tenant_id)
    references public.tenant_contacts(id, tenant_id),
  unique (id, tenant_id)
);

create table if not exists public.conversation_interactions (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  conversation_id bigint not null,
  channel_id bigint,
  primary_contact_id bigint,
  assigned_user_id bigint references public.auth_users(id) on delete set null,
  interaction_type text not null,
  direction text not null,
  status text not null default 'completed',
  provider text not null default 'voxalia',
  provider_ref text not null default '',
  started_at timestamptz,
  ended_at timestamptz,
  summary text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversation_interactions_type_ck check (interaction_type in ('voice_call', 'chat_message', 'email', 'note', 'handoff', 'system_event')),
  constraint conversation_interactions_direction_ck check (direction in ('inbound', 'outbound', 'internal')),
  constraint conversation_interactions_status_ck check (status in ('queued', 'active', 'completed', 'failed', 'cancelled')),
  constraint conversation_interactions_conversation_fk foreign key (conversation_id, tenant_id)
    references public.conversation_conversations(id, tenant_id) on delete cascade,
  constraint conversation_interactions_channel_fk foreign key (channel_id, tenant_id)
    references public.tenant_channels(id, tenant_id),
  constraint conversation_interactions_contact_fk foreign key (primary_contact_id, tenant_id)
    references public.conversation_contacts(id, tenant_id),
  constraint conversation_interactions_time_window_ck check (ended_at is null or started_at is null or ended_at >= started_at),
  unique (id, tenant_id)
);

create table if not exists public.conversation_notes (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  conversation_id bigint not null,
  interaction_id bigint,
  author_user_id bigint references public.auth_users(id) on delete set null,
  note_type text not null default 'manual',
  visibility text not null default 'internal',
  body text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversation_notes_type_ck check (note_type in ('manual', 'system', 'ai_assisted', 'handoff', 'correction')),
  constraint conversation_notes_visibility_ck check (visibility in ('internal', 'tenant_visible')),
  constraint conversation_notes_conversation_fk foreign key (conversation_id, tenant_id)
    references public.conversation_conversations(id, tenant_id) on delete cascade,
  constraint conversation_notes_interaction_fk foreign key (interaction_id, tenant_id)
    references public.conversation_interactions(id, tenant_id),
  unique (id, tenant_id)
);

create table if not exists public.conversation_outcomes (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  conversation_id bigint not null,
  interaction_id bigint,
  outcome_type text not null,
  outcome_status text not null default 'recorded',
  summary text not null default '',
  next_step text not null default '',
  created_by_user_id bigint references public.auth_users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversation_outcomes_type_ck check (outcome_type in ('booking_inquiry', 'reservation_change', 'message_taken', 'callback_requested', 'complaint', 'emergency', 'escalated', 'resolved', 'no_answer', 'other')),
  constraint conversation_outcomes_status_ck check (outcome_status in ('recorded', 'needs_follow_up', 'escalated', 'resolved', 'cancelled')),
  constraint conversation_outcomes_conversation_fk foreign key (conversation_id, tenant_id)
    references public.conversation_conversations(id, tenant_id) on delete cascade,
  constraint conversation_outcomes_interaction_fk foreign key (interaction_id, tenant_id)
    references public.conversation_interactions(id, tenant_id),
  unique (id, tenant_id)
);

create table if not exists public.conversation_opportunities (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  conversation_id bigint,
  contact_id bigint,
  owner_user_id bigint references public.auth_users(id) on delete set null,
  opportunity_type text not null default 'booking_inquiry',
  title text not null,
  stage text not null default 'new',
  status text not null default 'open',
  value_amount numeric(12,2),
  currency char(3) not null default 'USD',
  expected_close_at timestamptz,
  source text not null default 'conversation',
  notes text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversation_opportunities_type_ck check (opportunity_type in ('booking_inquiry', 'upsell', 'tour', 'transportation', 'group_event', 'reservation_recovery', 'other')),
  constraint conversation_opportunities_stage_ck check (stage in ('new', 'qualification', 'quoted', 'waiting_partner', 'won', 'lost')),
  constraint conversation_opportunities_status_ck check (status in ('open', 'won', 'lost', 'cancelled')),
  constraint conversation_opportunities_value_ck check (value_amount is null or value_amount >= 0),
  constraint conversation_opportunities_conversation_fk foreign key (conversation_id, tenant_id)
    references public.conversation_conversations(id, tenant_id),
  constraint conversation_opportunities_contact_fk foreign key (contact_id, tenant_id)
    references public.conversation_contacts(id, tenant_id),
  unique (id, tenant_id)
);

create table if not exists public.workflow_tasks (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  conversation_id bigint,
  interaction_id bigint,
  opportunity_id bigint,
  assigned_user_id bigint references public.auth_users(id) on delete set null,
  assigned_tenant_contact_id bigint,
  task_type text not null default 'follow_up',
  title text not null,
  description text not null default '',
  status text not null default 'open',
  priority text not null default 'normal',
  due_at timestamptz,
  completed_at timestamptz,
  created_by_user_id bigint references public.auth_users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint workflow_tasks_type_ck check (task_type in ('follow_up', 'callback', 'partner_handoff', 'reservation_check', 'complaint_review', 'quality_review', 'reporting', 'other')),
  constraint workflow_tasks_status_ck check (status in ('open', 'in_progress', 'blocked', 'completed', 'cancelled')),
  constraint workflow_tasks_priority_ck check (priority in ('low', 'normal', 'high', 'urgent')),
  constraint workflow_tasks_conversation_fk foreign key (conversation_id, tenant_id)
    references public.conversation_conversations(id, tenant_id),
  constraint workflow_tasks_interaction_fk foreign key (interaction_id, tenant_id)
    references public.conversation_interactions(id, tenant_id),
  constraint workflow_tasks_opportunity_fk foreign key (opportunity_id, tenant_id)
    references public.conversation_opportunities(id, tenant_id),
  constraint workflow_tasks_tenant_contact_fk foreign key (assigned_tenant_contact_id, tenant_id)
    references public.tenant_contacts(id, tenant_id),
  unique (id, tenant_id)
);

create table if not exists public.workflow_task_events (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  task_id bigint not null,
  event_type text not null,
  actor_user_id bigint references public.auth_users(id) on delete set null,
  note text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint workflow_task_events_task_fk foreign key (task_id, tenant_id)
    references public.workflow_tasks(id, tenant_id) on delete cascade
);

create table if not exists public.integration_connections (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  integration_key text not null,
  provider_type text not null,
  provider text not null,
  display_name text not null,
  status text not null default 'active',
  auth_mode text not null default 'none',
  secret_ref text not null default '',
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint integration_connections_provider_type_ck check (provider_type in ('asterisk', 'chatwoot', 'meta', 'pms', 'crm', 'email', 'payments', 'storage', 'other')),
  constraint integration_connections_status_ck check (status in ('active', 'inactive', 'provisioning', 'failed')),
  constraint integration_connections_auth_mode_ck check (auth_mode in ('none', 'api_key_ref', 'oauth_ref', 'basic_ref', 'webhook_secret_ref')),
  unique (id, tenant_id),
  unique (tenant_id, integration_key)
);

create table if not exists public.channel_provider_accounts (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  integration_connection_id bigint,
  provider_type text not null,
  provider_account_id text not null,
  display_name text not null,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint channel_provider_accounts_provider_type_ck check (provider_type in ('asterisk', 'chatwoot', 'meta', 'email', 'webchat', 'other')),
  constraint channel_provider_accounts_status_ck check (status in ('active', 'inactive', 'failed')),
  constraint channel_provider_accounts_connection_fk foreign key (integration_connection_id, tenant_id)
    references public.integration_connections(id, tenant_id),
  unique (id, tenant_id),
  unique (tenant_id, provider_type, provider_account_id)
);

create table if not exists public.channel_provider_mappings (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  channel_id bigint,
  provider_account_id bigint,
  provider_type text not null,
  provider_object_type text not null,
  provider_object_id text not null,
  internal_object_type text not null,
  internal_object_id text not null,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint channel_provider_mappings_status_ck check (status in ('active', 'inactive', 'failed')),
  constraint channel_provider_mappings_channel_fk foreign key (channel_id, tenant_id)
    references public.tenant_channels(id, tenant_id),
  constraint channel_provider_mappings_account_fk foreign key (provider_account_id, tenant_id)
    references public.channel_provider_accounts(id, tenant_id),
  unique (id, tenant_id),
  unique (tenant_id, provider_type, provider_object_type, provider_object_id)
);

create table if not exists public.integration_external_refs (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  integration_connection_id bigint,
  internal_object_type text not null,
  internal_object_id text not null,
  external_object_type text not null,
  external_object_id text not null,
  external_url text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint integration_external_refs_connection_fk foreign key (integration_connection_id, tenant_id)
    references public.integration_connections(id, tenant_id),
  unique (tenant_id, integration_connection_id, external_object_type, external_object_id)
);

create table if not exists public.integration_sync_jobs (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  integration_connection_id bigint,
  job_type text not null,
  status text not null default 'queued',
  cursor_value text not null default '',
  started_at timestamptz,
  finished_at timestamptz,
  error_message text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint integration_sync_jobs_status_ck check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  constraint integration_sync_jobs_connection_fk foreign key (integration_connection_id, tenant_id)
    references public.integration_connections(id, tenant_id),
  constraint integration_sync_jobs_time_window_ck check (finished_at is null or started_at is null or finished_at >= started_at)
);

create table if not exists public.integration_webhook_events (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  integration_connection_id bigint,
  provider text not null,
  event_type text not null,
  external_event_id text not null default '',
  status text not null default 'received',
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  error_message text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint integration_webhook_events_status_ck check (status in ('received', 'processed', 'ignored', 'failed')),
  constraint integration_webhook_events_connection_fk foreign key (integration_connection_id, tenant_id)
    references public.integration_connections(id, tenant_id)
);

create table if not exists public.asterisk_instance_status (
  id bigint generated by default as identity primary key,
  integration_connection_id bigint references public.integration_connections(id) on delete cascade,
  instance_key text not null,
  status text not null default 'unknown',
  asterisk_version text not null default '',
  freepbx_version text not null default '',
  last_seen_at timestamptz,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint asterisk_instance_status_status_ck check (status in ('healthy', 'degraded', 'down', 'unknown')),
  unique (instance_key)
);

create table if not exists public.asterisk_provider_mappings (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  integration_connection_id bigint references public.integration_connections(id) on delete cascade,
  mapping_type text not null,
  provider_object_id text not null,
  provider_label text not null default '',
  internal_object_type text not null,
  internal_object_id text not null,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint asterisk_provider_mappings_type_ck check (mapping_type in ('did', 'queue', 'extension', 'endpoint', 'recording_path', 'ami_event')),
  constraint asterisk_provider_mappings_status_ck check (status in ('active', 'inactive', 'failed')),
  unique (tenant_id, integration_connection_id, mapping_type, provider_object_id)
);

create table if not exists public.voice_call_sessions (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  conversation_id bigint,
  interaction_id bigint,
  channel_id bigint,
  number_id bigint,
  external_call_id text not null default '',
  correlation_id text not null,
  direction text not null,
  status text not null default 'ringing',
  caller_number_e164 text not null default '',
  called_number_e164 text not null default '',
  started_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz,
  duration_seconds integer,
  recording_state text not null default 'pending',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint voice_call_sessions_direction_ck check (direction in ('inbound', 'outbound', 'internal')),
  constraint voice_call_sessions_status_ck check (status in ('ringing', 'active', 'held', 'transferring', 'completed', 'failed', 'missed', 'abandoned')),
  constraint voice_call_sessions_recording_state_ck check (recording_state in ('pending', 'recording', 'available', 'failed', 'exempt')),
  constraint voice_call_sessions_duration_ck check (duration_seconds is null or duration_seconds >= 0),
  constraint voice_call_sessions_conversation_fk foreign key (conversation_id, tenant_id)
    references public.conversation_conversations(id, tenant_id),
  constraint voice_call_sessions_interaction_fk foreign key (interaction_id, tenant_id)
    references public.conversation_interactions(id, tenant_id),
  constraint voice_call_sessions_channel_fk foreign key (channel_id, tenant_id)
    references public.tenant_channels(id, tenant_id),
  constraint voice_call_sessions_number_fk foreign key (number_id, tenant_id)
    references public.voice_numbers(id, tenant_id),
  constraint voice_call_sessions_time_window_ck check (ended_at is null or ended_at >= started_at),
  unique (id, tenant_id),
  unique (correlation_id)
);

create table if not exists public.voice_call_legs (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  call_session_id bigint not null,
  leg_key text not null,
  party_type text not null,
  party_ref text not null default '',
  direction text not null,
  status text not null default 'ringing',
  started_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint voice_call_legs_party_type_ck check (party_type in ('caller', 'agent', 'tenant_contact', 'external', 'system')),
  constraint voice_call_legs_direction_ck check (direction in ('inbound', 'outbound', 'internal')),
  constraint voice_call_legs_status_ck check (status in ('ringing', 'active', 'held', 'completed', 'failed', 'cancelled')),
  constraint voice_call_legs_session_fk foreign key (call_session_id, tenant_id)
    references public.voice_call_sessions(id, tenant_id) on delete cascade,
  constraint voice_call_legs_time_window_ck check (ended_at is null or ended_at >= started_at),
  unique (id, tenant_id),
  unique (call_session_id, leg_key)
);

create table if not exists public.voice_call_events (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  call_session_id bigint not null,
  call_leg_id bigint,
  event_type text not null,
  provider text not null default 'asterisk',
  provider_event_id text not null default '',
  occurred_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint voice_call_events_session_fk foreign key (call_session_id, tenant_id)
    references public.voice_call_sessions(id, tenant_id) on delete cascade,
  constraint voice_call_events_leg_fk foreign key (call_leg_id, tenant_id)
    references public.voice_call_legs(id, tenant_id)
);

create table if not exists public.voice_recordings (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  call_session_id bigint not null,
  interaction_id bigint,
  recording_key text not null,
  status text not null default 'pending',
  started_at timestamptz,
  ended_at timestamptz,
  duration_seconds integer,
  storage_provider text not null default 'local',
  retention_until timestamptz,
  legal_hold boolean not null default false,
  failure_reason text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint voice_recordings_status_ck check (status in ('pending', 'available', 'failed', 'deleted')),
  constraint voice_recordings_duration_ck check (duration_seconds is null or duration_seconds >= 0),
  constraint voice_recordings_session_fk foreign key (call_session_id, tenant_id)
    references public.voice_call_sessions(id, tenant_id) on delete cascade,
  constraint voice_recordings_interaction_fk foreign key (interaction_id, tenant_id)
    references public.conversation_interactions(id, tenant_id),
  unique (id, tenant_id),
  unique (tenant_id, recording_key)
);

create table if not exists public.voice_recording_files (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  recording_id bigint not null,
  file_role text not null default 'source',
  storage_uri text not null,
  mime_type text not null default 'audio/wav',
  byte_size bigint,
  checksum_sha256 text not null default '',
  status text not null default 'available',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint voice_recording_files_role_ck check (file_role in ('source', 'normalized', 'redacted', 'clip')),
  constraint voice_recording_files_status_ck check (status in ('available', 'failed', 'deleted')),
  constraint voice_recording_files_size_ck check (byte_size is null or byte_size >= 0),
  constraint voice_recording_files_recording_fk foreign key (recording_id, tenant_id)
    references public.voice_recordings(id, tenant_id) on delete cascade,
  unique (id, tenant_id)
);

create table if not exists public.voice_recording_access_log (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  recording_id bigint not null,
  user_id bigint references public.auth_users(id) on delete set null,
  action text not null,
  reason text not null default '',
  ip_address inet,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint voice_recording_access_log_action_ck check (action in ('view_metadata', 'play', 'download', 'share_link', 'delete')),
  constraint voice_recording_access_log_recording_fk foreign key (recording_id, tenant_id)
    references public.voice_recordings(id, tenant_id) on delete cascade
);

create table if not exists public.ai_prompt_versions (
  id bigint generated by default as identity primary key,
  prompt_key text not null,
  version integer not null,
  purpose text not null,
  model_family text not null default '',
  prompt_text text not null,
  schema jsonb not null default '{}'::jsonb,
  status text not null default 'draft',
  created_by_user_id bigint references public.auth_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_prompt_versions_status_ck check (status in ('draft', 'active', 'retired')),
  constraint ai_prompt_versions_version_ck check (version > 0),
  unique (prompt_key, version)
);

create table if not exists public.ai_processing_jobs (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  job_type text not null,
  status text not null default 'queued',
  source_type text not null,
  source_id text not null,
  call_session_id bigint,
  recording_id bigint,
  interaction_id bigint,
  requested_by_user_id bigint references public.auth_users(id) on delete set null,
  started_at timestamptz,
  finished_at timestamptz,
  error_message text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_processing_jobs_type_ck check (job_type in ('transcription', 'summary', 'observation', 'extraction', 'quality_review', 'indexing')),
  constraint ai_processing_jobs_status_ck check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  constraint ai_processing_jobs_session_fk foreign key (call_session_id, tenant_id)
    references public.voice_call_sessions(id, tenant_id),
  constraint ai_processing_jobs_recording_fk foreign key (recording_id, tenant_id)
    references public.voice_recordings(id, tenant_id),
  constraint ai_processing_jobs_interaction_fk foreign key (interaction_id, tenant_id)
    references public.conversation_interactions(id, tenant_id),
  constraint ai_processing_jobs_time_window_ck check (finished_at is null or started_at is null or finished_at >= started_at),
  unique (id, tenant_id)
);

create table if not exists public.ai_model_runs (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  processing_job_id bigint,
  prompt_version_id bigint references public.ai_prompt_versions(id) on delete set null,
  provider text not null,
  model text not null,
  status text not null default 'running',
  input_tokens integer,
  output_tokens integer,
  cost_amount numeric(12,6),
  currency char(3) not null default 'USD',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  error_message text not null default '',
  request_metadata jsonb not null default '{}'::jsonb,
  response_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint ai_model_runs_status_ck check (status in ('running', 'succeeded', 'failed', 'cancelled')),
  constraint ai_model_runs_token_ck check ((input_tokens is null or input_tokens >= 0) and (output_tokens is null or output_tokens >= 0)),
  constraint ai_model_runs_cost_ck check (cost_amount is null or cost_amount >= 0),
  constraint ai_model_runs_job_fk foreign key (processing_job_id, tenant_id)
    references public.ai_processing_jobs(id, tenant_id)
);

create table if not exists public.ai_transcriptions (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  processing_job_id bigint,
  recording_id bigint not null,
  model_run_id bigint references public.ai_model_runs(id) on delete set null,
  language text not null default '',
  status text not null default 'completed',
  transcript_text text not null,
  confidence numeric(5,4),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_transcriptions_status_ck check (status in ('completed', 'partial', 'failed')),
  constraint ai_transcriptions_confidence_ck check (confidence is null or (confidence >= 0 and confidence <= 1)),
  constraint ai_transcriptions_job_fk foreign key (processing_job_id, tenant_id)
    references public.ai_processing_jobs(id, tenant_id),
  constraint ai_transcriptions_recording_fk foreign key (recording_id, tenant_id)
    references public.voice_recordings(id, tenant_id) on delete cascade,
  unique (id, tenant_id)
);

create table if not exists public.ai_transcript_segments (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  transcription_id bigint not null,
  segment_index integer not null,
  speaker_label text not null default '',
  starts_at_seconds numeric(10,3) not null,
  ends_at_seconds numeric(10,3) not null,
  text text not null,
  confidence numeric(5,4),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint ai_transcript_segments_index_ck check (segment_index >= 0),
  constraint ai_transcript_segments_time_ck check (ends_at_seconds >= starts_at_seconds),
  constraint ai_transcript_segments_confidence_ck check (confidence is null or (confidence >= 0 and confidence <= 1)),
  constraint ai_transcript_segments_transcription_fk foreign key (transcription_id, tenant_id)
    references public.ai_transcriptions(id, tenant_id) on delete cascade,
  unique (transcription_id, segment_index)
);

create table if not exists public.ai_call_summaries (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  processing_job_id bigint,
  call_session_id bigint,
  transcription_id bigint,
  model_run_id bigint references public.ai_model_runs(id) on delete set null,
  summary_type text not null default 'operational',
  summary text not null,
  status text not null default 'draft',
  approved_by_user_id bigint references public.auth_users(id) on delete set null,
  approved_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_call_summaries_type_ck check (summary_type in ('operational', 'tenant_report', 'qa', 'handoff')),
  constraint ai_call_summaries_status_ck check (status in ('draft', 'approved', 'rejected', 'superseded')),
  constraint ai_call_summaries_job_fk foreign key (processing_job_id, tenant_id)
    references public.ai_processing_jobs(id, tenant_id),
  constraint ai_call_summaries_session_fk foreign key (call_session_id, tenant_id)
    references public.voice_call_sessions(id, tenant_id),
  constraint ai_call_summaries_transcription_fk foreign key (transcription_id, tenant_id)
    references public.ai_transcriptions(id, tenant_id),
  unique (id, tenant_id)
);

create table if not exists public.ai_call_observations (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  call_session_id bigint,
  transcription_id bigint,
  model_run_id bigint references public.ai_model_runs(id) on delete set null,
  observation_type text not null,
  severity text not null default 'info',
  title text not null,
  body text not null default '',
  evidence jsonb not null default '{}'::jsonb,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_call_observations_severity_ck check (severity in ('info', 'low', 'medium', 'high', 'critical')),
  constraint ai_call_observations_status_ck check (status in ('open', 'reviewed', 'dismissed', 'resolved')),
  constraint ai_call_observations_session_fk foreign key (call_session_id, tenant_id)
    references public.voice_call_sessions(id, tenant_id),
  constraint ai_call_observations_transcription_fk foreign key (transcription_id, tenant_id)
    references public.ai_transcriptions(id, tenant_id),
  unique (id, tenant_id)
);

create table if not exists public.ai_extractions (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  processing_job_id bigint,
  source_type text not null,
  source_id text not null,
  extraction_type text not null,
  payload jsonb not null,
  confidence numeric(5,4),
  status text not null default 'pending_review',
  reviewed_by_user_id bigint references public.auth_users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_extractions_type_ck check (extraction_type in ('contact', 'task', 'opportunity', 'intent', 'sentiment', 'qa_signal', 'custom')),
  constraint ai_extractions_status_ck check (status in ('pending_review', 'accepted', 'rejected', 'applied')),
  constraint ai_extractions_confidence_ck check (confidence is null or (confidence >= 0 and confidence <= 1)),
  constraint ai_extractions_job_fk foreign key (processing_job_id, tenant_id)
    references public.ai_processing_jobs(id, tenant_id)
);

create table if not exists public.ai_quality_reviews (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  call_session_id bigint,
  model_run_id bigint references public.ai_model_runs(id) on delete set null,
  reviewer_user_id bigint references public.auth_users(id) on delete set null,
  status text not null default 'pending',
  score numeric(5,2),
  rubric jsonb not null default '{}'::jsonb,
  findings jsonb not null default '[]'::jsonb,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_quality_reviews_status_ck check (status in ('pending', 'reviewed', 'approved', 'rejected')),
  constraint ai_quality_reviews_score_ck check (score is null or (score >= 0 and score <= 100)),
  constraint ai_quality_reviews_session_fk foreign key (call_session_id, tenant_id)
    references public.voice_call_sessions(id, tenant_id),
  unique (id, tenant_id)
);

create table if not exists public.search_documents (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  source_type text not null,
  source_id text not null,
  title text not null default '',
  body text not null default '',
  language text not null default '',
  status text not null default 'active',
  indexed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint search_documents_status_ck check (status in ('active', 'stale', 'failed')),
  unique (id, tenant_id),
  unique (tenant_id, source_type, source_id)
);

create table if not exists public.search_document_chunks (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  document_id bigint not null,
  chunk_index integer not null,
  content text not null,
  token_count integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint search_document_chunks_index_ck check (chunk_index >= 0),
  constraint search_document_chunks_token_ck check (token_count is null or token_count >= 0),
  constraint search_document_chunks_document_fk foreign key (document_id, tenant_id)
    references public.search_documents(id, tenant_id) on delete cascade,
  unique (id, tenant_id),
  unique (document_id, chunk_index)
);

create table if not exists public.search_embeddings (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  chunk_id bigint not null,
  provider text not null,
  model text not null,
  dimensions integer not null,
  embedding double precision[] not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint search_embeddings_dimensions_ck check (dimensions > 0),
  constraint search_embeddings_chunk_fk foreign key (chunk_id, tenant_id)
    references public.search_document_chunks(id, tenant_id) on delete cascade,
  unique (chunk_id, provider, model)
);

create table if not exists public.search_index_jobs (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  job_type text not null default 'index',
  status text not null default 'queued',
  source_type text not null,
  source_id text not null,
  started_at timestamptz,
  finished_at timestamptz,
  error_message text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint search_index_jobs_type_ck check (job_type in ('index', 'reindex', 'delete', 'backfill')),
  constraint search_index_jobs_status_ck check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled'))
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  actor_user_id bigint references public.auth_users(id) on delete set null,
  event_type text not null,
  severity text not null default 'info',
  subject_type text not null,
  subject_id text not null default '',
  action text not null,
  outcome text not null default 'success',
  ip_address inet,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint audit_events_severity_ck check (severity in ('debug', 'info', 'warning', 'error', 'critical')),
  constraint audit_events_outcome_ck check (outcome in ('success', 'failure', 'denied', 'partial'))
);

create table if not exists public.audit_subject_links (
  id bigint generated by default as identity primary key,
  audit_event_id bigint not null references public.audit_events(id) on delete cascade,
  tenant_id bigint references public.tenants(id) on delete cascade,
  subject_type text not null,
  subject_id text not null,
  relationship text not null default 'related',
  created_at timestamptz not null default now()
);

create table if not exists public.call_audit_findings (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  call_session_id bigint not null,
  source_type text not null default 'ai',
  finding_type text not null,
  severity text not null default 'info',
  title text not null,
  description text not null default '',
  evidence jsonb not null default '{}'::jsonb,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint call_audit_findings_source_type_ck check (source_type in ('ai', 'human', 'system')),
  constraint call_audit_findings_severity_ck check (severity in ('info', 'low', 'medium', 'high', 'critical')),
  constraint call_audit_findings_status_ck check (status in ('open', 'reviewed', 'dismissed', 'resolved')),
  constraint call_audit_findings_session_fk foreign key (call_session_id, tenant_id)
    references public.voice_call_sessions(id, tenant_id) on delete cascade,
  unique (id, tenant_id)
);

create table if not exists public.call_audit_scores (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  call_session_id bigint not null,
  score_type text not null,
  score numeric(5,2) not null,
  max_score numeric(5,2) not null default 100,
  source_type text not null default 'ai',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint call_audit_scores_score_ck check (score >= 0 and max_score > 0 and score <= max_score),
  constraint call_audit_scores_source_type_ck check (source_type in ('ai', 'human', 'system')),
  constraint call_audit_scores_session_fk foreign key (call_session_id, tenant_id)
    references public.voice_call_sessions(id, tenant_id) on delete cascade
);

create table if not exists public.call_audit_reviews (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  call_session_id bigint not null,
  reviewer_user_id bigint references public.auth_users(id) on delete set null,
  status text not null default 'pending',
  decision text not null default '',
  notes text not null default '',
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint call_audit_reviews_status_ck check (status in ('pending', 'in_review', 'approved', 'rejected', 'needs_follow_up')),
  constraint call_audit_reviews_session_fk foreign key (call_session_id, tenant_id)
    references public.voice_call_sessions(id, tenant_id) on delete cascade,
  unique (id, tenant_id)
);

create index if not exists conversation_contacts_tenant_lookup_idx on public.conversation_contacts(tenant_id, status, phone_e164, email);
create index if not exists conversation_conversations_tenant_status_idx on public.conversation_conversations(tenant_id, status, updated_at desc);
create index if not exists conversation_participants_conversation_idx on public.conversation_participants(tenant_id, conversation_id);
create index if not exists conversation_interactions_conversation_idx on public.conversation_interactions(tenant_id, conversation_id, started_at desc);
create index if not exists conversation_notes_conversation_idx on public.conversation_notes(tenant_id, conversation_id, created_at desc);
create index if not exists conversation_outcomes_conversation_idx on public.conversation_outcomes(tenant_id, conversation_id, created_at desc);
create index if not exists conversation_opportunities_tenant_status_idx on public.conversation_opportunities(tenant_id, status, stage);
create index if not exists workflow_tasks_tenant_status_idx on public.workflow_tasks(tenant_id, status, due_at);
create index if not exists workflow_task_events_task_idx on public.workflow_task_events(tenant_id, task_id, created_at desc);

create index if not exists integration_connections_tenant_provider_idx on public.integration_connections(tenant_id, provider_type, status);
create index if not exists channel_provider_accounts_tenant_provider_idx on public.channel_provider_accounts(tenant_id, provider_type, status);
create index if not exists channel_provider_mappings_tenant_provider_idx on public.channel_provider_mappings(tenant_id, provider_type, provider_object_type);
create index if not exists integration_external_refs_lookup_idx on public.integration_external_refs(tenant_id, internal_object_type, internal_object_id);
create index if not exists integration_sync_jobs_status_idx on public.integration_sync_jobs(tenant_id, status, created_at desc);
create index if not exists integration_webhook_events_status_idx on public.integration_webhook_events(provider, status, received_at desc);
create index if not exists asterisk_provider_mappings_lookup_idx on public.asterisk_provider_mappings(tenant_id, mapping_type, provider_object_id);

create index if not exists voice_call_sessions_tenant_started_idx on public.voice_call_sessions(tenant_id, started_at desc);
create index if not exists voice_call_sessions_status_idx on public.voice_call_sessions(tenant_id, status, started_at desc);
create index if not exists voice_call_legs_session_idx on public.voice_call_legs(tenant_id, call_session_id);
create index if not exists voice_call_events_session_idx on public.voice_call_events(tenant_id, call_session_id, occurred_at desc);
create index if not exists voice_recordings_tenant_status_idx on public.voice_recordings(tenant_id, status, created_at desc);
create index if not exists voice_recording_files_recording_idx on public.voice_recording_files(tenant_id, recording_id);
create index if not exists voice_recording_access_log_recording_idx on public.voice_recording_access_log(tenant_id, recording_id, created_at desc);

create index if not exists ai_processing_jobs_status_idx on public.ai_processing_jobs(tenant_id, status, created_at desc);
create index if not exists ai_model_runs_job_idx on public.ai_model_runs(tenant_id, processing_job_id, started_at desc);
create index if not exists ai_transcriptions_recording_idx on public.ai_transcriptions(tenant_id, recording_id);
create index if not exists ai_transcript_segments_transcription_idx on public.ai_transcript_segments(tenant_id, transcription_id, segment_index);
create index if not exists ai_call_summaries_session_idx on public.ai_call_summaries(tenant_id, call_session_id, created_at desc);
create index if not exists ai_call_observations_session_idx on public.ai_call_observations(tenant_id, call_session_id, severity);
create index if not exists ai_extractions_source_idx on public.ai_extractions(tenant_id, source_type, source_id);
create index if not exists ai_quality_reviews_session_idx on public.ai_quality_reviews(tenant_id, call_session_id, created_at desc);

create index if not exists search_documents_source_idx on public.search_documents(tenant_id, source_type, source_id);
create index if not exists search_document_chunks_document_idx on public.search_document_chunks(tenant_id, document_id, chunk_index);
create index if not exists search_index_jobs_status_idx on public.search_index_jobs(tenant_id, status, created_at desc);

create index if not exists audit_events_tenant_created_idx on public.audit_events(tenant_id, created_at desc);
create index if not exists audit_events_subject_idx on public.audit_events(subject_type, subject_id, created_at desc);
create index if not exists audit_subject_links_subject_idx on public.audit_subject_links(subject_type, subject_id);
create index if not exists call_audit_findings_session_idx on public.call_audit_findings(tenant_id, call_session_id, status);
create index if not exists call_audit_scores_session_idx on public.call_audit_scores(tenant_id, call_session_id, score_type);
create index if not exists call_audit_reviews_session_idx on public.call_audit_reviews(tenant_id, call_session_id, status);

drop trigger if exists conversation_contacts_set_updated_at on public.conversation_contacts;
create trigger conversation_contacts_set_updated_at before update on public.conversation_contacts for each row execute function public.voxalia_set_updated_at();
drop trigger if exists conversation_conversations_set_updated_at on public.conversation_conversations;
create trigger conversation_conversations_set_updated_at before update on public.conversation_conversations for each row execute function public.voxalia_set_updated_at();
drop trigger if exists conversation_participants_set_updated_at on public.conversation_participants;
create trigger conversation_participants_set_updated_at before update on public.conversation_participants for each row execute function public.voxalia_set_updated_at();
drop trigger if exists conversation_interactions_set_updated_at on public.conversation_interactions;
create trigger conversation_interactions_set_updated_at before update on public.conversation_interactions for each row execute function public.voxalia_set_updated_at();
drop trigger if exists conversation_notes_set_updated_at on public.conversation_notes;
create trigger conversation_notes_set_updated_at before update on public.conversation_notes for each row execute function public.voxalia_set_updated_at();
drop trigger if exists conversation_outcomes_set_updated_at on public.conversation_outcomes;
create trigger conversation_outcomes_set_updated_at before update on public.conversation_outcomes for each row execute function public.voxalia_set_updated_at();
drop trigger if exists conversation_opportunities_set_updated_at on public.conversation_opportunities;
create trigger conversation_opportunities_set_updated_at before update on public.conversation_opportunities for each row execute function public.voxalia_set_updated_at();
drop trigger if exists workflow_tasks_set_updated_at on public.workflow_tasks;
create trigger workflow_tasks_set_updated_at before update on public.workflow_tasks for each row execute function public.voxalia_set_updated_at();
drop trigger if exists integration_connections_set_updated_at on public.integration_connections;
create trigger integration_connections_set_updated_at before update on public.integration_connections for each row execute function public.voxalia_set_updated_at();
drop trigger if exists channel_provider_accounts_set_updated_at on public.channel_provider_accounts;
create trigger channel_provider_accounts_set_updated_at before update on public.channel_provider_accounts for each row execute function public.voxalia_set_updated_at();
drop trigger if exists channel_provider_mappings_set_updated_at on public.channel_provider_mappings;
create trigger channel_provider_mappings_set_updated_at before update on public.channel_provider_mappings for each row execute function public.voxalia_set_updated_at();
drop trigger if exists integration_external_refs_set_updated_at on public.integration_external_refs;
create trigger integration_external_refs_set_updated_at before update on public.integration_external_refs for each row execute function public.voxalia_set_updated_at();
drop trigger if exists integration_sync_jobs_set_updated_at on public.integration_sync_jobs;
create trigger integration_sync_jobs_set_updated_at before update on public.integration_sync_jobs for each row execute function public.voxalia_set_updated_at();
drop trigger if exists asterisk_instance_status_set_updated_at on public.asterisk_instance_status;
create trigger asterisk_instance_status_set_updated_at before update on public.asterisk_instance_status for each row execute function public.voxalia_set_updated_at();
drop trigger if exists asterisk_provider_mappings_set_updated_at on public.asterisk_provider_mappings;
create trigger asterisk_provider_mappings_set_updated_at before update on public.asterisk_provider_mappings for each row execute function public.voxalia_set_updated_at();
drop trigger if exists voice_call_sessions_set_updated_at on public.voice_call_sessions;
create trigger voice_call_sessions_set_updated_at before update on public.voice_call_sessions for each row execute function public.voxalia_set_updated_at();
drop trigger if exists voice_call_legs_set_updated_at on public.voice_call_legs;
create trigger voice_call_legs_set_updated_at before update on public.voice_call_legs for each row execute function public.voxalia_set_updated_at();
drop trigger if exists voice_recordings_set_updated_at on public.voice_recordings;
create trigger voice_recordings_set_updated_at before update on public.voice_recordings for each row execute function public.voxalia_set_updated_at();
drop trigger if exists voice_recording_files_set_updated_at on public.voice_recording_files;
create trigger voice_recording_files_set_updated_at before update on public.voice_recording_files for each row execute function public.voxalia_set_updated_at();
drop trigger if exists ai_prompt_versions_set_updated_at on public.ai_prompt_versions;
create trigger ai_prompt_versions_set_updated_at before update on public.ai_prompt_versions for each row execute function public.voxalia_set_updated_at();
drop trigger if exists ai_processing_jobs_set_updated_at on public.ai_processing_jobs;
create trigger ai_processing_jobs_set_updated_at before update on public.ai_processing_jobs for each row execute function public.voxalia_set_updated_at();
drop trigger if exists ai_transcriptions_set_updated_at on public.ai_transcriptions;
create trigger ai_transcriptions_set_updated_at before update on public.ai_transcriptions for each row execute function public.voxalia_set_updated_at();
drop trigger if exists ai_call_summaries_set_updated_at on public.ai_call_summaries;
create trigger ai_call_summaries_set_updated_at before update on public.ai_call_summaries for each row execute function public.voxalia_set_updated_at();
drop trigger if exists ai_call_observations_set_updated_at on public.ai_call_observations;
create trigger ai_call_observations_set_updated_at before update on public.ai_call_observations for each row execute function public.voxalia_set_updated_at();
drop trigger if exists ai_extractions_set_updated_at on public.ai_extractions;
create trigger ai_extractions_set_updated_at before update on public.ai_extractions for each row execute function public.voxalia_set_updated_at();
drop trigger if exists ai_quality_reviews_set_updated_at on public.ai_quality_reviews;
create trigger ai_quality_reviews_set_updated_at before update on public.ai_quality_reviews for each row execute function public.voxalia_set_updated_at();
drop trigger if exists search_documents_set_updated_at on public.search_documents;
create trigger search_documents_set_updated_at before update on public.search_documents for each row execute function public.voxalia_set_updated_at();
drop trigger if exists search_document_chunks_set_updated_at on public.search_document_chunks;
create trigger search_document_chunks_set_updated_at before update on public.search_document_chunks for each row execute function public.voxalia_set_updated_at();
drop trigger if exists search_index_jobs_set_updated_at on public.search_index_jobs;
create trigger search_index_jobs_set_updated_at before update on public.search_index_jobs for each row execute function public.voxalia_set_updated_at();
drop trigger if exists call_audit_findings_set_updated_at on public.call_audit_findings;
create trigger call_audit_findings_set_updated_at before update on public.call_audit_findings for each row execute function public.voxalia_set_updated_at();
drop trigger if exists call_audit_reviews_set_updated_at on public.call_audit_reviews;
create trigger call_audit_reviews_set_updated_at before update on public.call_audit_reviews for each row execute function public.voxalia_set_updated_at();
