-- Voxalia Asterisk control-plane foundation.
-- This schema belongs to services/asterisk, not services/web-api.
-- It models desired/applied Asterisk state and does not duplicate FreePBX
-- internals such as trunks, PJSIP passwords, devices or generated dialplan DB.

create schema if not exists asterisk;

create table if not exists asterisk.dial_contexts (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  context_key text not null,
  display_name text not null,
  provider text not null default 'asterisk',
  provider_context_name text not null,
  direction text not null,
  status text not null default 'active',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dial_contexts_context_key_ck check (context_key in ('inbound', 'internal', 'outbound', 'queue', 'after_hours', 'emergency', 'recording', 'test')),
  constraint dial_contexts_direction_ck check (direction in ('inbound', 'internal', 'outbound', 'mixed')),
  constraint dial_contexts_status_ck check (status in ('active', 'inactive', 'draft', 'failed')),
  unique (id, tenant_id),
  unique (tenant_id, context_key),
  unique (provider, provider_context_name)
);

create table if not exists asterisk.logical_extensions (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  dial_context_id bigint not null,
  logical_extension text not null,
  display_name text not null,
  extension_type text not null default 'agent',
  provider_endpoint text not null,
  status text not null default 'active',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint logical_extensions_type_ck check (extension_type in ('agent', 'supervisor', 'tenant_contact', 'test', 'system')),
  constraint logical_extensions_status_ck check (status in ('active', 'inactive', 'provisioning', 'failed')),
  constraint logical_extensions_context_fk foreign key (dial_context_id, tenant_id)
    references asterisk.dial_contexts(id, tenant_id) on delete cascade,
  unique (id, tenant_id),
  unique (tenant_id, dial_context_id, logical_extension),
  unique (provider_endpoint)
);

create table if not exists asterisk.logical_queues (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  dial_context_id bigint not null,
  queue_key text not null,
  display_name text not null,
  provider_queue_name text not null,
  strategy text not null default 'ringall',
  timeout_seconds integer not null default 30,
  recording_required boolean not null default true,
  status text not null default 'active',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint logical_queues_strategy_ck check (strategy in ('ringall', 'leastrecent', 'fewestcalls', 'random', 'rrmemory', 'linear')),
  constraint logical_queues_status_ck check (status in ('active', 'inactive', 'provisioning', 'failed')),
  constraint logical_queues_timeout_ck check (timeout_seconds > 0),
  constraint logical_queues_context_fk foreign key (dial_context_id, tenant_id)
    references asterisk.dial_contexts(id, tenant_id) on delete cascade,
  unique (id, tenant_id),
  unique (tenant_id, queue_key),
  unique (provider_queue_name)
);

create table if not exists asterisk.logical_queue_members (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  logical_queue_id bigint not null,
  logical_extension_id bigint not null,
  penalty integer not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint logical_queue_members_penalty_ck check (penalty >= 0),
  constraint logical_queue_members_status_ck check (status in ('active', 'paused', 'inactive')),
  constraint logical_queue_members_queue_fk foreign key (logical_queue_id, tenant_id)
    references asterisk.logical_queues(id, tenant_id) on delete cascade,
  constraint logical_queue_members_extension_fk foreign key (logical_extension_id, tenant_id)
    references asterisk.logical_extensions(id, tenant_id) on delete cascade,
  unique (logical_queue_id, logical_extension_id)
);

create table if not exists asterisk.routing_rules (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  channel_id bigint,
  number_id bigint,
  inbound_context_id bigint,
  target_type text not null,
  target_id text not null,
  priority integer not null default 100,
  recording_required boolean not null default true,
  status text not null default 'active',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint routing_rules_target_type_ck check (target_type in ('queue', 'extension', 'context', 'external_number', 'voicemail', 'hangup')),
  constraint routing_rules_status_ck check (status in ('active', 'inactive', 'provisioning', 'failed')),
  constraint routing_rules_priority_ck check (priority >= 0),
  constraint routing_rules_channel_fk foreign key (channel_id, tenant_id)
    references public.tenant_channels(id, tenant_id),
  constraint routing_rules_number_fk foreign key (number_id, tenant_id)
    references public.voice_numbers(id, tenant_id),
  constraint routing_rules_context_fk foreign key (inbound_context_id, tenant_id)
    references asterisk.dial_contexts(id, tenant_id),
  unique (id, tenant_id)
);

create table if not exists asterisk.recording_policies (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  policy_key text not null,
  display_name text not null,
  scope_type text not null,
  scope_id text not null,
  recording_required boolean not null default true,
  disclosure_required boolean not null default true,
  retention_days integer not null default 365,
  storage_path_template text not null default '',
  status text not null default 'active',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recording_policies_scope_type_ck check (scope_type in ('tenant', 'channel', 'number', 'queue', 'extension')),
  constraint recording_policies_status_ck check (status in ('active', 'inactive', 'draft')),
  constraint recording_policies_retention_ck check (retention_days > 0),
  unique (tenant_id, policy_key)
);

create table if not exists asterisk.provider_mappings (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  mapping_type text not null,
  provider_object_id text not null,
  provider_label text not null default '',
  internal_object_type text not null,
  internal_object_id text not null,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_mappings_type_ck check (mapping_type in ('did', 'context', 'queue', 'extension', 'endpoint', 'recording_path', 'ami_event', 'ari_app')),
  constraint provider_mappings_status_ck check (status in ('active', 'inactive', 'failed')),
  unique (tenant_id, mapping_type, provider_object_id)
);

create table if not exists asterisk.provisioning_jobs (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  job_type text not null,
  status text not null default 'queued',
  requested_by_user_id bigint references public.auth_users(id) on delete set null,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  error_message text not null default '',
  desired_state jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provisioning_jobs_type_ck check (job_type in ('render_config', 'apply_config', 'reload', 'rollback', 'drift_check')),
  constraint provisioning_jobs_status_ck check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  constraint provisioning_jobs_time_window_ck check (finished_at is null or started_at is null or finished_at >= started_at)
);

create table if not exists asterisk.config_revisions (
  id bigint generated by default as identity primary key,
  revision_key text not null unique,
  tenant_id bigint references public.tenants(id) on delete cascade,
  provisioning_job_id bigint references asterisk.provisioning_jobs(id) on delete set null,
  status text not null default 'generated',
  config_hash text not null,
  rendered_config jsonb not null default '{}'::jsonb,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  constraint config_revisions_status_ck check (status in ('generated', 'applied', 'failed', 'rolled_back'))
);

create table if not exists asterisk.applied_objects (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  config_revision_id bigint references asterisk.config_revisions(id) on delete cascade,
  object_type text not null,
  object_key text not null,
  provider_object_id text not null,
  config_hash text not null default '',
  status text not null default 'applied',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint applied_objects_status_ck check (status in ('applied', 'failed', 'removed', 'drifted')),
  unique (tenant_id, object_type, object_key)
);

create table if not exists asterisk.drift_checks (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  config_revision_id bigint references asterisk.config_revisions(id) on delete set null,
  status text not null default 'queued',
  expected_hash text not null default '',
  observed_hash text not null default '',
  details jsonb not null default '{}'::jsonb,
  checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint drift_checks_status_ck check (status in ('queued', 'running', 'in_sync', 'drift_detected', 'failed'))
);

create table if not exists asterisk.instance_status (
  id bigint generated by default as identity primary key,
  instance_key text not null unique,
  status text not null default 'unknown',
  asterisk_version text not null default '',
  endpoint text not null default '',
  last_seen_at timestamptz,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instance_status_status_ck check (status in ('healthy', 'degraded', 'down', 'unknown'))
);

grant usage on schema asterisk to voxalia_app;
grant usage on schema asterisk to voxalia_admin;

grant all privileges on all tables in schema asterisk to voxalia_app;
grant all privileges on all sequences in schema asterisk to voxalia_app;
grant execute on all functions in schema asterisk to voxalia_app;

grant all privileges on all tables in schema asterisk to voxalia_admin;
grant all privileges on all sequences in schema asterisk to voxalia_admin;
grant execute on all functions in schema asterisk to voxalia_admin;

alter default privileges in schema asterisk
  grant all privileges on tables to voxalia_app;

alter default privileges in schema asterisk
  grant all privileges on sequences to voxalia_app;

alter default privileges in schema asterisk
  grant execute on functions to voxalia_app;

alter default privileges in schema asterisk
  grant all privileges on tables to voxalia_admin;

alter default privileges in schema asterisk
  grant all privileges on sequences to voxalia_admin;

alter default privileges in schema asterisk
  grant execute on functions to voxalia_admin;

create index if not exists dial_contexts_tenant_idx on asterisk.dial_contexts(tenant_id, status);
create index if not exists logical_extensions_tenant_idx on asterisk.logical_extensions(tenant_id, status, logical_extension);
create index if not exists logical_queues_tenant_idx on asterisk.logical_queues(tenant_id, status);
create index if not exists routing_rules_tenant_idx on asterisk.routing_rules(tenant_id, status, priority);
create index if not exists recording_policies_tenant_idx on asterisk.recording_policies(tenant_id, status);
create index if not exists provider_mappings_lookup_idx on asterisk.provider_mappings(tenant_id, mapping_type, provider_object_id);
create index if not exists provisioning_jobs_status_idx on asterisk.provisioning_jobs(status, requested_at desc);
create index if not exists applied_objects_revision_idx on asterisk.applied_objects(config_revision_id);
create index if not exists drift_checks_status_idx on asterisk.drift_checks(status, created_at desc);

create or replace function asterisk.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists dial_contexts_set_updated_at on asterisk.dial_contexts;
create trigger dial_contexts_set_updated_at before update on asterisk.dial_contexts for each row execute function asterisk.set_updated_at();
drop trigger if exists logical_extensions_set_updated_at on asterisk.logical_extensions;
create trigger logical_extensions_set_updated_at before update on asterisk.logical_extensions for each row execute function asterisk.set_updated_at();
drop trigger if exists logical_queues_set_updated_at on asterisk.logical_queues;
create trigger logical_queues_set_updated_at before update on asterisk.logical_queues for each row execute function asterisk.set_updated_at();
drop trigger if exists logical_queue_members_set_updated_at on asterisk.logical_queue_members;
create trigger logical_queue_members_set_updated_at before update on asterisk.logical_queue_members for each row execute function asterisk.set_updated_at();
drop trigger if exists routing_rules_set_updated_at on asterisk.routing_rules;
create trigger routing_rules_set_updated_at before update on asterisk.routing_rules for each row execute function asterisk.set_updated_at();
drop trigger if exists recording_policies_set_updated_at on asterisk.recording_policies;
create trigger recording_policies_set_updated_at before update on asterisk.recording_policies for each row execute function asterisk.set_updated_at();
drop trigger if exists provider_mappings_set_updated_at on asterisk.provider_mappings;
create trigger provider_mappings_set_updated_at before update on asterisk.provider_mappings for each row execute function asterisk.set_updated_at();
drop trigger if exists provisioning_jobs_set_updated_at on asterisk.provisioning_jobs;
create trigger provisioning_jobs_set_updated_at before update on asterisk.provisioning_jobs for each row execute function asterisk.set_updated_at();
drop trigger if exists applied_objects_set_updated_at on asterisk.applied_objects;
create trigger applied_objects_set_updated_at before update on asterisk.applied_objects for each row execute function asterisk.set_updated_at();
drop trigger if exists drift_checks_set_updated_at on asterisk.drift_checks;
create trigger drift_checks_set_updated_at before update on asterisk.drift_checks for each row execute function asterisk.set_updated_at();
drop trigger if exists instance_status_set_updated_at on asterisk.instance_status;
create trigger instance_status_set_updated_at before update on asterisk.instance_status for each row execute function asterisk.set_updated_at();

insert into public.tenants (id, tenant_key, display_name, legal_name, vertical, timezone, status, metadata)
values (
  2,
  'hotel-valle-azul',
  'Hotel Valle Azul',
  'Hotel Valle Azul',
  'hospitality',
  'America/Costa_Rica',
  'active',
  '{"seed":"asterisk-initial-tests"}'::jsonb
)
on conflict (id) do update set
  tenant_key = excluded.tenant_key,
  display_name = excluded.display_name,
  legal_name = excluded.legal_name,
  vertical = excluded.vertical,
  timezone = excluded.timezone,
  status = excluded.status,
  metadata = excluded.metadata,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.tenants', 'id'),
  greatest((select coalesce(max(id), 1) from public.tenants), 1)
);

with tenant_row as (
  select id as tenant_id from public.tenants where tenant_key = 'hotel-valle-azul'
),
inserted_contexts as (
  insert into asterisk.dial_contexts (tenant_id, context_key, display_name, provider_context_name, direction, config)
  select tenant_id, context_key, display_name, provider_context_name, direction, config
  from tenant_row
  cross join (
    values
      ('inbound', 'Hotel Valle Azul inbound', 'tenant_hotel_valle_azul_inbound', 'inbound', '{"purpose":"did-entry"}'::jsonb),
      ('internal', 'Hotel Valle Azul internal', 'tenant_hotel_valle_azul_internal', 'internal', '{"purpose":"logical-extensions"}'::jsonb),
      ('outbound', 'Hotel Valle Azul outbound', 'tenant_hotel_valle_azul_outbound', 'outbound', '{"purpose":"tenant-outbound"}'::jsonb),
      ('queue', 'Hotel Valle Azul queues', 'tenant_hotel_valle_azul_queue', 'mixed', '{"purpose":"managed-reception-queues"}'::jsonb),
      ('after_hours', 'Hotel Valle Azul after-hours', 'tenant_hotel_valle_azul_after_hours', 'inbound', '{"purpose":"closed-hours"}'::jsonb)
  ) as seed(context_key, display_name, provider_context_name, direction, config)
  on conflict (tenant_id, context_key) do update set
    display_name = excluded.display_name,
    provider_context_name = excluded.provider_context_name,
    direction = excluded.direction,
    config = excluded.config,
    updated_at = now()
  returning id, tenant_id, context_key
),
internal_context as (
  select id, tenant_id from asterisk.dial_contexts
  where tenant_id = (select tenant_id from tenant_row) and context_key = 'internal'
),
queue_context as (
  select id, tenant_id from asterisk.dial_contexts
  where tenant_id = (select tenant_id from tenant_row) and context_key = 'queue'
),
extensions as (
  insert into asterisk.logical_extensions (tenant_id, dial_context_id, logical_extension, display_name, extension_type, provider_endpoint, config)
  select tenant_id, id, logical_extension, display_name, 'test', provider_endpoint, config
  from internal_context
  cross join (
    values
      ('3001', 'Valle Azul Test Extension 3001', 'hotel-valle-azul-3001', '{"freepbx_lab_extension":"3001"}'::jsonb),
      ('3002', 'Valle Azul Test Extension 3002', 'hotel-valle-azul-3002', '{"freepbx_lab_extension":"3002"}'::jsonb)
  ) as seed(logical_extension, display_name, provider_endpoint, config)
  on conflict (tenant_id, dial_context_id, logical_extension) do update set
    display_name = excluded.display_name,
    extension_type = excluded.extension_type,
    provider_endpoint = excluded.provider_endpoint,
    config = excluded.config,
    updated_at = now()
  returning id, tenant_id, logical_extension
),
queue_row as (
  insert into asterisk.logical_queues (tenant_id, dial_context_id, queue_key, display_name, provider_queue_name, strategy, timeout_seconds, recording_required, config)
  select tenant_id, id, 'front-desk', 'Hotel Valle Azul Front Desk', 'hotel-valle-azul-front-desk', 'ringall', 30, true, '{"freepbx_lab_queue":"front-desk"}'::jsonb
  from queue_context
  on conflict (tenant_id, queue_key) do update set
    display_name = excluded.display_name,
    provider_queue_name = excluded.provider_queue_name,
    strategy = excluded.strategy,
    timeout_seconds = excluded.timeout_seconds,
    recording_required = excluded.recording_required,
    config = excluded.config,
    updated_at = now()
  returning id, tenant_id
)
insert into asterisk.logical_queue_members (tenant_id, logical_queue_id, logical_extension_id, penalty)
select e.tenant_id, q.id, e.id, 0
from extensions e
cross join queue_row q
on conflict (logical_queue_id, logical_extension_id) do update set
  penalty = excluded.penalty,
  status = 'active',
  updated_at = now();

insert into asterisk.logical_extensions (tenant_id, dial_context_id, logical_extension, display_name, extension_type, provider_endpoint, config)
select dc.tenant_id, dc.id, seed.logical_extension, seed.display_name, 'test', seed.provider_endpoint, seed.config
from asterisk.dial_contexts dc
cross join (
  values
    ('3001', 'Valle Azul Test Extension 3001', 'hotel-valle-azul-3001', '{"freepbx_lab_extension":"3001"}'::jsonb),
    ('3002', 'Valle Azul Test Extension 3002', 'hotel-valle-azul-3002', '{"freepbx_lab_extension":"3002"}'::jsonb)
) as seed(logical_extension, display_name, provider_endpoint, config)
where dc.tenant_id = 2
  and dc.context_key = 'internal'
on conflict (tenant_id, dial_context_id, logical_extension) do update set
  display_name = excluded.display_name,
  extension_type = excluded.extension_type,
  provider_endpoint = excluded.provider_endpoint,
  config = excluded.config,
  updated_at = now();

insert into asterisk.logical_queues (tenant_id, dial_context_id, queue_key, display_name, provider_queue_name, strategy, timeout_seconds, recording_required, config)
select dc.tenant_id, dc.id, 'front-desk', 'Hotel Valle Azul Front Desk', 'hotel-valle-azul-front-desk', 'ringall', 30, true, '{"freepbx_lab_queue":"front-desk"}'::jsonb
from asterisk.dial_contexts dc
where dc.tenant_id = 2
  and dc.context_key = 'queue'
on conflict (tenant_id, queue_key) do update set
  display_name = excluded.display_name,
  provider_queue_name = excluded.provider_queue_name,
  strategy = excluded.strategy,
  timeout_seconds = excluded.timeout_seconds,
  recording_required = excluded.recording_required,
  config = excluded.config,
  updated_at = now();

insert into asterisk.logical_queue_members (tenant_id, logical_queue_id, logical_extension_id, penalty)
select q.tenant_id, q.id, e.id, 0
from asterisk.logical_queues q
join asterisk.logical_extensions e on e.tenant_id = q.tenant_id
where q.tenant_id = 2
  and q.queue_key = 'front-desk'
  and e.logical_extension in ('3001', '3002')
on conflict (logical_queue_id, logical_extension_id) do update set
  penalty = excluded.penalty,
  status = 'active',
  updated_at = now();
