-- Tenant-level Asterisk voice profiles.
-- This is the entry point for Settings > Asterisk. It does not duplicate
-- public.tenants business data; it stores Asterisk provisioning posture.

create table if not exists asterisk.tenant_voice_profiles (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  voice_enabled boolean not null default true,
  provisioning_mode text not null default 'generated',
  namespace_key text not null,
  default_context_prefix text not null,
  default_extension_prefix text not null default '',
  status text not null default 'active',
  last_provisioned_at timestamptz,
  last_drift_check_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_voice_profiles_mode_ck check (provisioning_mode in ('manual', 'generated', 'hybrid')),
  constraint tenant_voice_profiles_status_ck check (status in ('active', 'paused', 'provisioning', 'failed')),
  unique (tenant_id),
  unique (namespace_key),
  unique (default_context_prefix)
);

create index if not exists tenant_voice_profiles_status_idx
  on asterisk.tenant_voice_profiles(status, voice_enabled);

drop trigger if exists tenant_voice_profiles_set_updated_at on asterisk.tenant_voice_profiles;
create trigger tenant_voice_profiles_set_updated_at
before update on asterisk.tenant_voice_profiles
for each row execute function asterisk.set_updated_at();

insert into asterisk.tenant_voice_profiles (
  tenant_id,
  voice_enabled,
  provisioning_mode,
  namespace_key,
  default_context_prefix,
  default_extension_prefix,
  status,
  metadata
)
select
  id,
  true,
  case when tenant_key = 'voxalia' then 'hybrid' else 'generated' end,
  tenant_key,
  'tenant_' || replace(tenant_key, '-', '_'),
  case when tenant_key = 'hotel-valle-azul' then '3' else '' end,
  'active',
  jsonb_build_object('seed', 'tenant-voice-profile')
from public.tenants
where tenant_key in ('voxalia', 'hotel-valle-azul')
on conflict (tenant_id) do update set
  voice_enabled = excluded.voice_enabled,
  provisioning_mode = excluded.provisioning_mode,
  namespace_key = excluded.namespace_key,
  default_context_prefix = excluded.default_context_prefix,
  default_extension_prefix = excluded.default_extension_prefix,
  status = excluded.status,
  metadata = excluded.metadata,
  updated_at = now();

grant all privileges on all tables in schema asterisk to voxalia_app;
grant all privileges on all sequences in schema asterisk to voxalia_app;
grant execute on all functions in schema asterisk to voxalia_app;

grant all privileges on all tables in schema asterisk to voxalia_admin;
grant all privileges on all sequences in schema asterisk to voxalia_admin;
grant execute on all functions in schema asterisk to voxalia_admin;
