-- Declarative dialplan flow catalog.
-- Voxalia stores safe, provider-neutral actions. The Asterisk provisioner later
-- renders these actions into concrete Asterisk dialplan applications.

create table if not exists asterisk.dialplan_action_catalog (
  id bigint generated by default as identity primary key,
  action_key text not null unique,
  label text not null,
  description text not null default '',
  category text not null,
  requires_target boolean not null default false,
  parameter_schema jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dialplan_action_catalog_category_ck check (category in ('call_control', 'recording', 'routing', 'policy', 'workflow', 'system')),
  constraint dialplan_action_catalog_status_ck check (status in ('active', 'inactive'))
);

create table if not exists asterisk.context_action_rules (
  id bigint generated by default as identity primary key,
  context_key text not null,
  action_key text not null references asterisk.dialplan_action_catalog(action_key) on delete cascade,
  allowed boolean not null default true,
  default_enabled boolean not null default false,
  sort_order integer not null default 100,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint context_action_rules_context_key_ck check (context_key in ('inbound', 'internal', 'outbound', 'queue', 'after_hours', 'emergency', 'recording', 'test')),
  constraint context_action_rules_sort_order_ck check (sort_order >= 0),
  unique (context_key, action_key)
);

create table if not exists asterisk.dialplan_flows (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  dial_context_id bigint not null,
  flow_key text not null,
  display_name text not null,
  entry_extension text not null default 's',
  status text not null default 'active',
  version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dialplan_flows_status_ck check (status in ('active', 'inactive', 'draft')),
  constraint dialplan_flows_version_ck check (version > 0),
  constraint dialplan_flows_context_fk foreign key (dial_context_id, tenant_id)
    references asterisk.dial_contexts(id, tenant_id) on delete cascade,
  unique (id, tenant_id),
  unique (tenant_id, dial_context_id, flow_key, version)
);

create table if not exists asterisk.dialplan_steps (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  dialplan_flow_id bigint not null,
  step_order integer not null,
  action_key text not null references asterisk.dialplan_action_catalog(action_key) on delete restrict,
  label text not null default '',
  parameters jsonb not null default '{}'::jsonb,
  on_success_step_order integer,
  on_failure_step_order integer,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dialplan_steps_step_order_ck check (step_order > 0),
  constraint dialplan_steps_status_ck check (status in ('active', 'inactive', 'draft')),
  constraint dialplan_steps_flow_fk foreign key (dialplan_flow_id, tenant_id)
    references asterisk.dialplan_flows(id, tenant_id) on delete cascade,
  unique (dialplan_flow_id, step_order)
);

create index if not exists dialplan_action_catalog_category_idx
  on asterisk.dialplan_action_catalog(category, status);

create index if not exists context_action_rules_context_idx
  on asterisk.context_action_rules(context_key, allowed, sort_order);

create index if not exists dialplan_flows_context_idx
  on asterisk.dialplan_flows(tenant_id, dial_context_id, status);

create index if not exists dialplan_steps_flow_idx
  on asterisk.dialplan_steps(tenant_id, dialplan_flow_id, step_order);

drop trigger if exists dialplan_action_catalog_set_updated_at on asterisk.dialplan_action_catalog;
create trigger dialplan_action_catalog_set_updated_at
before update on asterisk.dialplan_action_catalog
for each row execute function asterisk.set_updated_at();

drop trigger if exists context_action_rules_set_updated_at on asterisk.context_action_rules;
create trigger context_action_rules_set_updated_at
before update on asterisk.context_action_rules
for each row execute function asterisk.set_updated_at();

drop trigger if exists dialplan_flows_set_updated_at on asterisk.dialplan_flows;
create trigger dialplan_flows_set_updated_at
before update on asterisk.dialplan_flows
for each row execute function asterisk.set_updated_at();

drop trigger if exists dialplan_steps_set_updated_at on asterisk.dialplan_steps;
create trigger dialplan_steps_set_updated_at
before update on asterisk.dialplan_steps
for each row execute function asterisk.set_updated_at();

insert into asterisk.dialplan_action_catalog (action_key, label, description, category, requires_target, parameter_schema)
values
  ('answer', 'Answer', 'Answer the channel before playback, recording or routing.', 'call_control', false, '{}'::jsonb),
  ('play_disclosure', 'Play disclosure', 'Play tenant-approved recording disclosure or informational prompt.', 'policy', false, '{"script_key":"string"}'::jsonb),
  ('start_recording', 'Start recording', 'Start tenant-scoped recording according to recording policy.', 'recording', false, '{"policy_key":"string"}'::jsonb),
  ('check_business_hours', 'Check business hours', 'Branch based on the tenant service policy schedule.', 'policy', true, '{"service_policy_key":"string","open_target":"string","closed_target":"string"}'::jsonb),
  ('route_to_queue', 'Route to queue', 'Send the call to a tenant logical queue.', 'routing', true, '{"queue_key":"string"}'::jsonb),
  ('route_to_extension', 'Route to extension', 'Route the call to a tenant logical extension.', 'routing', true, '{"logical_extension":"string"}'::jsonb),
  ('route_to_context', 'Route to context', 'Move execution to another tenant dial context.', 'routing', true, '{"context_key":"string","entry_extension":"string"}'::jsonb),
  ('set_caller_id', 'Set caller ID', 'Set outbound caller ID based on tenant policy.', 'call_control', false, '{"caller_id":"string"}'::jsonb),
  ('dial_external', 'Dial external', 'Dial an external PSTN destination using tenant outbound policy.', 'routing', true, '{"destination":"string"}'::jsonb),
  ('take_message', 'Take message', 'Capture a message or voicemail-style follow-up for the tenant.', 'workflow', false, '{"task_type":"string"}'::jsonb),
  ('create_task', 'Create task', 'Create a Voxalia follow-up task from call flow state.', 'workflow', false, '{"task_type":"string","priority":"string"}'::jsonb),
  ('emit_event', 'Emit event', 'Emit an internal Voxalia event for observability or workflow.', 'system', false, '{"event_type":"string"}'::jsonb),
  ('hangup', 'Hangup', 'Terminate the call cleanly.', 'call_control', false, '{}'::jsonb)
on conflict (action_key) do update set
  label = excluded.label,
  description = excluded.description,
  category = excluded.category,
  requires_target = excluded.requires_target,
  parameter_schema = excluded.parameter_schema,
  status = 'active',
  updated_at = now();

insert into asterisk.context_action_rules (context_key, action_key, allowed, default_enabled, sort_order)
values
  ('inbound', 'answer', true, true, 10),
  ('inbound', 'play_disclosure', true, true, 20),
  ('inbound', 'start_recording', true, true, 30),
  ('inbound', 'check_business_hours', true, true, 40),
  ('inbound', 'route_to_queue', true, true, 50),
  ('inbound', 'route_to_context', true, true, 60),
  ('inbound', 'create_task', true, false, 70),
  ('inbound', 'emit_event', true, true, 80),
  ('inbound', 'hangup', true, true, 90),
  ('after_hours', 'answer', true, true, 10),
  ('after_hours', 'play_disclosure', true, true, 20),
  ('after_hours', 'take_message', true, true, 30),
  ('after_hours', 'create_task', true, true, 40),
  ('after_hours', 'route_to_extension', true, false, 50),
  ('after_hours', 'emit_event', true, true, 60),
  ('after_hours', 'hangup', true, true, 70),
  ('internal', 'route_to_extension', true, true, 10),
  ('internal', 'route_to_queue', true, true, 20),
  ('internal', 'emit_event', true, true, 30),
  ('internal', 'hangup', true, true, 40),
  ('outbound', 'set_caller_id', true, true, 10),
  ('outbound', 'start_recording', true, true, 20),
  ('outbound', 'dial_external', true, true, 30),
  ('outbound', 'emit_event', true, true, 40),
  ('outbound', 'hangup', true, true, 50),
  ('queue', 'route_to_queue', true, true, 10),
  ('queue', 'route_to_extension', true, true, 20),
  ('queue', 'emit_event', true, true, 30),
  ('queue', 'hangup', true, true, 40)
on conflict (context_key, action_key) do update set
  allowed = excluded.allowed,
  default_enabled = excluded.default_enabled,
  sort_order = excluded.sort_order,
  updated_at = now();

with tenant_row as (
  select id as tenant_id from public.tenants where tenant_key = 'hotel-valle-azul'
),
flow_seed as (
  select
    dc.tenant_id,
    dc.id as dial_context_id,
    seed.flow_key,
    seed.display_name,
    seed.entry_extension,
    seed.metadata
  from asterisk.dial_contexts dc
  join tenant_row t on t.tenant_id = dc.tenant_id
  join (
    values
      ('inbound', 'main-inbound', 'Main inbound flow', 's', '{"purpose":"did-entry"}'::jsonb),
      ('after_hours', 'after-hours-message', 'After-hours message flow', 's', '{"purpose":"closed-hours"}'::jsonb),
      ('internal', 'internal-extension-routing', 'Internal extension routing', '_3XXX', '{"purpose":"tenant-extension-namespace"}'::jsonb),
      ('outbound', 'main-outbound', 'Main outbound flow', '_X.', '{"purpose":"tenant-outbound"}'::jsonb),
      ('queue', 'front-desk-queue', 'Front desk queue flow', 'front-desk', '{"purpose":"managed-reception-queue"}'::jsonb)
  ) as seed(context_key, flow_key, display_name, entry_extension, metadata) on seed.context_key = dc.context_key
)
insert into asterisk.dialplan_flows (tenant_id, dial_context_id, flow_key, display_name, entry_extension, status, version, metadata)
select tenant_id, dial_context_id, flow_key, display_name, entry_extension, 'active', 1, metadata
from flow_seed
on conflict (tenant_id, dial_context_id, flow_key, version) do update set
  display_name = excluded.display_name,
  entry_extension = excluded.entry_extension,
  status = excluded.status,
  metadata = excluded.metadata,
  updated_at = now();

with flow_rows as (
  select f.id, f.tenant_id, f.flow_key
  from asterisk.dialplan_flows f
  join public.tenants t on t.id = f.tenant_id
  where t.tenant_key = 'hotel-valle-azul'
),
step_seed as (
  select * from (
    values
      ('main-inbound', 10, 'answer', 'Answer inbound call', '{}'::jsonb),
      ('main-inbound', 20, 'play_disclosure', 'Play recording disclosure', '{"script_key":"recording-disclosure"}'::jsonb),
      ('main-inbound', 30, 'start_recording', 'Start required recording', '{"policy_key":"default"}'::jsonb),
      ('main-inbound', 40, 'check_business_hours', 'Route by service hours', '{"service_policy_key":"default","open_target":"queue:front-desk","closed_target":"context:after_hours"}'::jsonb),
      ('main-inbound', 50, 'route_to_queue', 'Send to front desk queue', '{"queue_key":"front-desk"}'::jsonb),
      ('after-hours-message', 10, 'answer', 'Answer after-hours call', '{}'::jsonb),
      ('after-hours-message', 20, 'play_disclosure', 'Play after-hours message', '{"script_key":"after-hours"}'::jsonb),
      ('after-hours-message', 30, 'take_message', 'Take callback message', '{"task_type":"callback"}'::jsonb),
      ('after-hours-message', 40, 'create_task', 'Create next-day callback', '{"task_type":"callback","priority":"normal"}'::jsonb),
      ('after-hours-message', 50, 'hangup', 'End after-hours call', '{}'::jsonb),
      ('internal-extension-routing', 10, 'route_to_extension', 'Route to matching 3xxx extension', '{"logical_extension":"${EXTEN}"}'::jsonb),
      ('internal-extension-routing', 20, 'emit_event', 'Emit internal routing event', '{"event_type":"asterisk.internal_route"}'::jsonb),
      ('main-outbound', 10, 'set_caller_id', 'Set tenant outbound caller ID', '{"caller_id":"tenant_default"}'::jsonb),
      ('main-outbound', 20, 'start_recording', 'Start outbound recording', '{"policy_key":"default"}'::jsonb),
      ('main-outbound', 30, 'dial_external', 'Dial external destination', '{"destination":"${EXTEN}"}'::jsonb),
      ('main-outbound', 40, 'emit_event', 'Emit outbound call event', '{"event_type":"asterisk.outbound_route"}'::jsonb),
      ('front-desk-queue', 10, 'emit_event', 'Emit queue entered event', '{"event_type":"asterisk.queue_entered","queue_key":"front-desk"}'::jsonb),
      ('front-desk-queue', 20, 'route_to_queue', 'Ring front desk queue', '{"queue_key":"front-desk"}'::jsonb),
      ('front-desk-queue', 30, 'create_task', 'Create missed-call follow-up on timeout', '{"task_type":"callback","priority":"high"}'::jsonb)
  ) as seed(flow_key, step_order, action_key, label, parameters)
)
insert into asterisk.dialplan_steps (tenant_id, dialplan_flow_id, step_order, action_key, label, parameters, status)
select f.tenant_id, f.id, s.step_order, s.action_key, s.label, s.parameters, 'active'
from flow_rows f
join step_seed s on s.flow_key = f.flow_key
on conflict (dialplan_flow_id, step_order) do update set
  action_key = excluded.action_key,
  label = excluded.label,
  parameters = excluded.parameters,
  status = excluded.status,
  updated_at = now();

grant all privileges on all tables in schema asterisk to voxalia_app;
grant all privileges on all sequences in schema asterisk to voxalia_app;
grant execute on all functions in schema asterisk to voxalia_app;

grant all privileges on all tables in schema asterisk to voxalia_admin;
grant all privileges on all sequences in schema asterisk to voxalia_admin;
grant execute on all functions in schema asterisk to voxalia_admin;
