-- Extension device mappings.
-- A queue member points to a logical extension; this table defines where that
-- extension can actually ring or register.

create table if not exists asterisk.extension_devices (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  logical_extension_id bigint not null,
  device_key text not null,
  display_name text not null,
  device_type text not null,
  provider_endpoint text not null,
  registration_mode text not null,
  status text not null default 'active',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint extension_devices_type_ck check (device_type in ('web_phone', 'sip_phone', 'mobile_softphone', 'desktop_softphone', 'external_forward')),
  constraint extension_devices_registration_mode_ck check (registration_mode in ('generated_credentials', 'manual_credentials', 'external_number', 'managed_app')),
  constraint extension_devices_status_ck check (status in ('active', 'inactive', 'provisioning', 'failed')),
  constraint extension_devices_extension_fk foreign key (logical_extension_id, tenant_id)
    references asterisk.logical_extensions(id, tenant_id) on delete cascade,
  unique (id, tenant_id),
  unique (tenant_id, logical_extension_id, device_key),
  unique (provider_endpoint)
);

create index if not exists extension_devices_extension_idx
  on asterisk.extension_devices(tenant_id, logical_extension_id, status);

drop trigger if exists extension_devices_set_updated_at on asterisk.extension_devices;
create trigger extension_devices_set_updated_at
before update on asterisk.extension_devices
for each row execute function asterisk.set_updated_at();

grant all privileges on all tables in schema asterisk to voxalia_app;
grant all privileges on all sequences in schema asterisk to voxalia_app;
grant all privileges on all tables in schema asterisk to voxalia_admin;
grant all privileges on all sequences in schema asterisk to voxalia_admin;

with extension_rows as (
  select
    le.id as logical_extension_id,
    le.tenant_id,
    le.logical_extension
  from asterisk.logical_extensions le
  join public.tenants t on t.id = le.tenant_id
  where t.tenant_key = 'hotel-valle-azul'
    and le.logical_extension in ('3001', '3002', '3003', '3004')
)
insert into asterisk.extension_devices (
  tenant_id,
  logical_extension_id,
  device_key,
  display_name,
  device_type,
  provider_endpoint,
  registration_mode,
  status,
  config
)
select
  e.tenant_id,
  e.logical_extension_id,
  seed.device_key,
  seed.display_name,
  seed.device_type,
  seed.provider_endpoint,
  seed.registration_mode,
  'active',
  seed.config
from extension_rows e
join (
  values
    ('3001', 'web-pc', 'Reception PC web phone', 'web_phone', 'hotel-valle-azul-3001-web-pc', 'managed_app', '{"test_seed":true,"location":"front_desk"}'::jsonb),
    ('3001', 'sip-desk', 'Reception desk SIP phone', 'sip_phone', 'hotel-valle-azul-3001-sip-desk', 'generated_credentials', '{"test_seed":true,"location":"front_desk"}'::jsonb),
    ('3002', 'mobile-app', 'Reception mobile softphone', 'mobile_softphone', 'hotel-valle-azul-3002-mobile-app', 'managed_app', '{"test_seed":true,"platform":"mobile"}'::jsonb),
    ('3003', 'desktop-softphone', 'Reservations desktop softphone', 'desktop_softphone', 'hotel-valle-azul-3003-desktop-softphone', 'manual_credentials', '{"test_seed":true,"team":"reservations"}'::jsonb),
    ('3004', 'supervisor-forward', 'Supervisor external forward', 'external_forward', 'hotel-valle-azul-3004-forward', 'external_number', '{"test_seed":true,"forward_target":"masked"}'::jsonb)
) as seed(logical_extension, device_key, display_name, device_type, provider_endpoint, registration_mode, config)
  on seed.logical_extension = e.logical_extension
on conflict (tenant_id, logical_extension_id, device_key) do update set
  display_name = excluded.display_name,
  device_type = excluded.device_type,
  provider_endpoint = excluded.provider_endpoint,
  registration_mode = excluded.registration_mode,
  status = excluded.status,
  config = excluded.config,
  updated_at = now();
