-- Global SIP trunk intent for Asterisk PJSIP provisioning.
-- A PJSIP trunk is rendered into endpoint/aor/auth/registration/identify
-- objects later; this table stores Voxalia's provider-neutral desired state
-- without SIP secrets.

create table if not exists asterisk.sip_trunks (
  id bigint generated by default as identity primary key,
  trunk_key text not null unique,
  display_name text not null,
  carrier_name text not null default '',
  provider_endpoint text not null,
  transport text not null default 'udp',
  trunk_role text not null default 'bidirectional',
  registration_mode text not null default 'outbound_registration',
  auth_mode text not null default 'outbound_auth',
  match_strategy text not null default 'ip',
  remote_hosts text not null default '',
  codecs text not null default 'ulaw,alaw',
  max_channels integer not null default 0,
  status text not null default 'active',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sip_trunks_key_ck check (trunk_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  constraint sip_trunks_transport_ck check (transport in ('udp', 'tcp', 'tls', 'ws', 'wss')),
  constraint sip_trunks_role_ck check (trunk_role in ('inbound', 'outbound', 'bidirectional')),
  constraint sip_trunks_registration_mode_ck check (registration_mode in ('none', 'outbound_registration', 'inbound_registration')),
  constraint sip_trunks_auth_mode_ck check (auth_mode in ('none', 'outbound_auth', 'inbound_auth', 'mutual')),
  constraint sip_trunks_match_strategy_ck check (match_strategy in ('ip', 'line', 'header', 'registration')),
  constraint sip_trunks_status_ck check (status in ('active', 'inactive', 'provisioning', 'failed')),
  constraint sip_trunks_max_channels_ck check (max_channels >= 0)
);

create index if not exists sip_trunks_status_idx
  on asterisk.sip_trunks(status, trunk_role);

drop trigger if exists sip_trunks_set_updated_at on asterisk.sip_trunks;
create trigger sip_trunks_set_updated_at
before update on asterisk.sip_trunks
for each row execute function asterisk.set_updated_at();

insert into asterisk.sip_trunks (
  trunk_key,
  display_name,
  carrier_name,
  provider_endpoint,
  transport,
  trunk_role,
  registration_mode,
  auth_mode,
  match_strategy,
  remote_hosts,
  codecs,
  max_channels,
  status,
  config
)
values (
  'lab-freepbx',
  'Lab FreePBX trunk',
  'FreePBX Lab',
  'sip:freepbx.local',
  'udp',
  'bidirectional',
  'none',
  'none',
  'ip',
  'freepbx',
  'ulaw,alaw',
  0,
  'active',
  '{"seed":true,"purpose":"lab-connectivity-placeholder"}'::jsonb
)
on conflict (trunk_key) do nothing;

grant all privileges on all tables in schema asterisk to voxalia_app;
grant all privileges on all sequences in schema asterisk to voxalia_app;
grant all privileges on all tables in schema asterisk to voxalia_admin;
grant all privileges on all sequences in schema asterisk to voxalia_admin;
