-- Global carrier/provider catalog for Asterisk connectivity.
-- Carriers are not native Asterisk PJSIP objects; they describe provider
-- accounts and support posture used by one or more trunks.

create table if not exists asterisk.carriers (
  id bigint generated by default as identity primary key,
  carrier_key text not null unique,
  display_name text not null,
  provider_name text not null,
  account_scope text not null default 'global',
  region text not null default 'us',
  support_status text not null default 'standard',
  failover_policy text not null default 'manual',
  status text not null default 'active',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint carriers_key_ck check (carrier_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  constraint carriers_account_scope_ck check (account_scope in ('global', 'regional', 'tenant_dedicated', 'lab')),
  constraint carriers_support_status_ck check (support_status in ('standard', 'premium', 'limited', 'unsupported')),
  constraint carriers_failover_policy_ck check (failover_policy in ('manual', 'automatic', 'none')),
  constraint carriers_status_ck check (status in ('active', 'inactive', 'provisioning', 'failed'))
);

create index if not exists carriers_status_idx
  on asterisk.carriers(status, account_scope);

drop trigger if exists carriers_set_updated_at on asterisk.carriers;
create trigger carriers_set_updated_at
before update on asterisk.carriers
for each row execute function asterisk.set_updated_at();

insert into asterisk.carriers (
  carrier_key,
  display_name,
  provider_name,
  account_scope,
  region,
  support_status,
  failover_policy,
  status,
  config
)
values (
  'freepbx-lab',
  'FreePBX Lab',
  'FreePBX Lab',
  'lab',
  'local',
  'limited',
  'manual',
  'active',
  '{"seed":true,"purpose":"lab-provider-placeholder"}'::jsonb
)
on conflict (carrier_key) do nothing;

grant all privileges on all tables in schema asterisk to voxalia_app;
grant all privileges on all sequences in schema asterisk to voxalia_app;
grant all privileges on all tables in schema asterisk to voxalia_admin;
grant all privileges on all sequences in schema asterisk to voxalia_admin;
