-- Logical inventory of Asterisk runtime nodes controlled or monitored by Voxalia.
-- Secrets stay in environment/secrets management; this table stores only
-- operator-visible metadata, health posture and provisioning target intent.

create table if not exists asterisk.instances (
  id bigint generated by default as identity primary key,
  instance_key text not null unique,
  display_name text not null,
  environment text not null default 'dev',
  role text not null default 'standalone',
  control_mode text not null default 'config_render',
  endpoint_ref text not null,
  region text not null default 'local',
  asterisk_version text not null default '',
  capabilities text not null default 'pjsip,queues,recording',
  status text not null default 'active',
  health_status text not null default 'unknown',
  last_seen_at timestamptz,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instances_key_ck check (instance_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  constraint instances_environment_ck check (environment in ('dev', 'staging', 'production', 'lab')),
  constraint instances_role_ck check (role in ('standalone', 'primary', 'secondary', 'worker')),
  constraint instances_control_mode_ck check (control_mode in ('config_render', 'ami', 'ari', 'ssh', 'manual')),
  constraint instances_status_ck check (status in ('active', 'inactive', 'maintenance', 'provisioning', 'failed')),
  constraint instances_health_status_ck check (health_status in ('unknown', 'healthy', 'degraded', 'offline'))
);

create index if not exists instances_status_idx
  on asterisk.instances(status, environment);

drop trigger if exists instances_set_updated_at on asterisk.instances;
create trigger instances_set_updated_at
before update on asterisk.instances
for each row execute function asterisk.set_updated_at();

insert into asterisk.instances (
  instance_key,
  display_name,
  environment,
  role,
  control_mode,
  endpoint_ref,
  region,
  asterisk_version,
  capabilities,
  status,
  health_status,
  config
)
values (
  'asterisk-local',
  'Asterisk Local',
  'dev',
  'standalone',
  'config_render',
  'env:VOXALIA_ASTERISK_RUNTIME',
  'local',
  '',
  'pjsip,queues,recording',
  'active',
  'unknown',
  '{"seed":true,"purpose":"local-development-runtime"}'::jsonb
)
on conflict (instance_key) do nothing;

grant all privileges on all tables in schema asterisk to voxalia_app;
grant all privileges on all sequences in schema asterisk to voxalia_app;
grant all privileges on all tables in schema asterisk to voxalia_admin;
grant all privileges on all sequences in schema asterisk to voxalia_admin;
