-- Agent to tenant extension mappings.
-- This is the bridge between Voxalia operator profiles and Asterisk logical
-- extensions. Queue membership can keep pointing to logical extensions, while
-- the UI can reason in terms of human agents.

create table if not exists asterisk.agent_extension_assignments (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  agent_profile_id bigint not null references public.agent_profiles(id) on delete cascade,
  logical_extension_id bigint not null,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_extension_assignments_status_ck check (status in ('active', 'inactive', 'provisioning', 'failed')),
  constraint agent_extension_assignments_extension_fk foreign key (logical_extension_id, tenant_id)
    references asterisk.logical_extensions(id, tenant_id) on delete cascade,
  unique (id, tenant_id),
  unique (tenant_id, agent_profile_id, logical_extension_id)
);

create unique index if not exists agent_extension_assignments_one_active_idx
  on asterisk.agent_extension_assignments(tenant_id, agent_profile_id)
  where status = 'active';

create index if not exists agent_extension_assignments_agent_idx
  on asterisk.agent_extension_assignments(agent_profile_id, status);

create index if not exists agent_extension_assignments_tenant_idx
  on asterisk.agent_extension_assignments(tenant_id, status);

drop trigger if exists agent_extension_assignments_set_updated_at on asterisk.agent_extension_assignments;
create trigger agent_extension_assignments_set_updated_at
before update on asterisk.agent_extension_assignments
for each row execute function asterisk.set_updated_at();

grant all privileges on all tables in schema asterisk to voxalia_app;
grant all privileges on all sequences in schema asterisk to voxalia_app;
grant all privileges on all tables in schema asterisk to voxalia_admin;
grant all privileges on all sequences in schema asterisk to voxalia_admin;
